/**
 * Java emitter: maps the SqliteHost IR to Java source files. Three file
 * families, all golden-tested byte-for-byte against the committed Java
 * sources under java/sqlite-host-model:
 *
 *  1. Envelope model records/classes (Script, Step, Statement,
 *     RuntimeInput, BindingValue) in io.sqlitehost.model.envelope.
 *  2. Host method DTO records in <namespace-lowercased>.generated.
 *  3. A MethodDescriptors class mirroring the manifest method metadata.
 *
 * Paths are relative to a Java source root (package dirs included), so
 * callers decide which source tree the files land in.
 */

import {
  toSnakeCase,
  type HostLibraryIr,
  type HostMethodIr,
  type ListFieldIr,
  type ObjectShapeIr,
  type ScalarFieldIr,
  type ScalarTypeIr,
} from "@sqlite-host/codegen-core";

export interface EmittedFile {
  /** Path relative to a Java source root (e.g. "io/sqlitehost/...java"). */
  path: string;
  contents: string;
}

/** Java package of the envelope model (fixed per protocol, not per IR). */
export const ENVELOPE_PACKAGE = "io.sqlitehost.model.envelope";

const MAX_LINE = 80;

/** All Java files for the IR: envelope model, DTOs, method descriptors. */
export function emitJava(ir: HostLibraryIr): EmittedFile[] {
  return [
    ...emitEnvelopeModel(ir),
    ...emitHostMethodDtos(ir),
    emitMethodDescriptors(ir),
  ];
}

/** Generated package name: library namespace lowercased + ".generated". */
export function generatedPackageName(ir: HostLibraryIr): string {
  return ir.library.namespace.toLowerCase() + ".generated";
}

function packagePath(packageName: string, typeName: string): string {
  return packageName.split(".").join("/") + "/" + typeName + ".java";
}

function javaString(value: string): string {
  return '"' + value.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}

function javaScalarType(type: ScalarTypeIr, optional: boolean): string {
  switch (type) {
    case "int32":
      return optional ? "Integer" : "int";
    case "int64":
      return optional ? "Long" : "long";
    case "boolean":
      return optional ? "Boolean" : "boolean";
    case "string":
      return "String";
    case "bytes":
      return "byte[]";
    case "float32":
      return optional ? "Float" : "float";
    case "float64":
      return optional ? "Double" : "double";
  }
}

// ---------------------------------------------------------------------------
// Envelope model (io.sqlitehost.model.envelope)
// ---------------------------------------------------------------------------

function envelopeHeader(engine: string): string {
  return `// <auto-generated />
// Generated-style projection of the SqliteHost script envelope
// (typespec/library, protocol ${engine}). Kept in sync with the
// cross-language contract (docs/script-envelope.md) by golden tests;
// do not edit independently of that contract.
package ${ENVELOPE_PACKAGE};
`;
}

/** The five envelope model files (protocol-shaped; engine + binding types
 *  come from the IR's scriptEnvelope block). */
export function emitEnvelopeModel(ir: HostLibraryIr): EmittedFile[] {
  const header = envelopeHeader(ir.scriptEnvelope.engine);
  return [
    {
      path: packagePath(ENVELOPE_PACKAGE, "Script"),
      contents: scriptSource(header, ir.scriptEnvelope.engine),
    },
    { path: packagePath(ENVELOPE_PACKAGE, "Step"), contents: stepSource(header) },
    {
      path: packagePath(ENVELOPE_PACKAGE, "Statement"),
      contents: statementSource(header),
    },
    {
      path: packagePath(ENVELOPE_PACKAGE, "RuntimeInput"),
      contents: runtimeInputSource(header, ir.inputsTable.name),
    },
    {
      path: packagePath(ENVELOPE_PACKAGE, "BindingValue"),
      contents: bindingValueSource(header, ir.scriptEnvelope.bindingTypes),
    },
  ];
}

function scriptSource(header: string, engine: string): string {
  return `${header}
import java.util.Collections;
import java.util.List;

/**
 * The parsed script envelope (protocol v1). Field semantics follow
 * docs/script-envelope.md; fields that are optional on the wire are
 * empty lists (or {@code null} for scalars) when absent. Structural
 * validity is the validator's job, not this model's.
 */
public record Script(
        String engine,
        String scriptId,
        Integer requiredApiLevel,
        List<String> requiredFeatures,
        List<String> requiredMethods,
        List<RuntimeInput> inputs,
        List<Step> steps) {

    /** The only engine value understood by protocol v1. */
    public static final String ENGINE_V1 = ${javaString(engine)};

    public Script {
        requiredFeatures = copyOrEmpty(requiredFeatures);
        requiredMethods = copyOrEmpty(requiredMethods);
        inputs = copyOrEmpty(inputs);
        steps = copyOrEmpty(steps);
    }

    private static <T> List<T> copyOrEmpty(List<T> list) {
        return list == null ? Collections.emptyList() : List.copyOf(list);
    }
}
`;
}

function stepSource(header: string): string {
  return `${header}
import java.util.Collections;
import java.util.List;

/**
 * One ordered script step. Statements run in order within the step;
 * the runtime drains pending host calls only after all statements of
 * the step succeeded.
 */
public record Step(String id, List<Statement> statements) {

    public Step {
        statements = statements == null
                ? Collections.emptyList()
                : List.copyOf(statements);
    }
}
`;
}

function statementSource(header: string): string {
  return `${header}
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * One SQL statement of a step: the SQL text plus its named bindings
 * (bare names, no {@code :}/{@code @}/{@code $} prefix).
 */
public record Statement(String sql, Map<String, BindingValue> bindings) {

    public Statement {
        bindings = bindings == null
                ? Collections.emptyMap()
                : Collections.unmodifiableMap(new LinkedHashMap<>(bindings));
    }
}
`;
}

function runtimeInputSource(header: string, inputsTable: string): string {
  return `${header}
/**
 * A runtime input inserted into the {@code ${inputsTable}} table before
 * the first step runs.
 */
public record RuntimeInput(String name, BindingValue value) {
}
`;
}

/** Per-binding-type snippets of the BindingValue class. Keyed by the wire
 *  name; the IR's bindingTypes list selects and orders the entries. */
interface BindingTypeParts {
  factory: string;
  accessor?: string;
  toStringBody: string;
}

function bindingTypeParts(wire: string): BindingTypeParts {
  const constName = wire.toUpperCase();
  switch (wire) {
    case "null":
      return {
        factory: `    /** The {@code null} binding value. */
    public static BindingValue nullValue() {
        return NULL_VALUE;
    }`,
        toStringBody: `return "BindingValue[null]";`,
      };
    case "int32":
    case "int64":
      return {
        factory: `    /** An {@code ${wire}} binding value. */
    public static BindingValue ${wire}(${wire === "int32" ? "int" : "long"} value) {
        return new BindingValue(Type.${constName}, value, 0.0, null, null);
    }`,
        accessor: `    /** @throws IllegalStateException when {@link #type()} is not {@code ${constName}} */
    public ${wire === "int32" ? "int" : "long"} as${constName.charAt(0)}${wire.slice(1)}() {
        requireType(Type.${constName});
        return ${wire === "int32" ? "(int) integerValue" : "integerValue"};
    }`,
        toStringBody: `return "BindingValue[" + type.jsonName() + " " + integerValue + "]";`,
      };
    case "bool":
      return {
        factory: `    /** A {@code bool} binding value. */
    public static BindingValue bool(boolean value) {
        return new BindingValue(Type.BOOL, value ? 1L : 0L, 0.0, null, null);
    }`,
        accessor: `    /** @throws IllegalStateException when {@link #type()} is not {@code BOOL} */
    public boolean asBool() {
        requireType(Type.BOOL);
        return integerValue != 0L;
    }`,
        toStringBody: `return "BindingValue[bool " + (integerValue != 0L) + "]";`,
      };
    case "text":
      return {
        factory: `    /** A {@code text} binding value. */
    public static BindingValue text(String value) {
        Objects.requireNonNull(value, "value");
        return new BindingValue(Type.TEXT, 0L, 0.0, value, null);
    }`,
        accessor: `    /** @throws IllegalStateException when {@link #type()} is not {@code TEXT} */
    public String asText() {
        requireType(Type.TEXT);
        return textValue;
    }`,
        toStringBody: `return "BindingValue[text " + textValue + "]";`,
      };
    case "blob":
      return {
        factory: `    /** A {@code blob} binding value (the byte array is copied). */
    public static BindingValue blob(byte[] value) {
        Objects.requireNonNull(value, "value");
        return new BindingValue(Type.BLOB, 0L, 0.0, null, value.clone());
    }`,
        accessor: `    /**
     * A copy of the blob bytes.
     *
     * @throws IllegalStateException when {@link #type()} is not {@code BLOB}
     */
    public byte[] asBlob() {
        requireType(Type.BLOB);
        return blobValue.clone();
    }`,
        toStringBody: `return "BindingValue[blob " + blobValue.length + " bytes]";`,
      };
    case "float32":
    case "float64":
      return {
        factory: `    /**
     * A {@code ${wire}} binding value.
     *
     * @throws IllegalArgumentException when the value is not finite
     *     (NaN/Infinity have no JSON representation, docs/script-envelope.md)
     */
    public static BindingValue ${wire}(${wire === "float32" ? "float" : "double"} value) {
        if (!${wire === "float32" ? "Float" : "Double"}.isFinite(value)) {
            throw new IllegalArgumentException("${wire} value must be finite: " + value);
        }
        return new BindingValue(Type.${constName}, 0L, value, null, null);
    }`,
        accessor: `    /** @throws IllegalStateException when {@link #type()} is not {@code ${constName}} */
    public ${wire === "float32" ? "float" : "double"} as${constName.charAt(0)}${wire.slice(1)}() {
        requireType(Type.${constName});
        return ${wire === "float32" ? "(float) realValue" : "realValue"};
    }`,
        toStringBody: `return "BindingValue[" + type.jsonName() + " " + realValue + "]";`,
      };
    default:
      throw new Error(`unsupported envelope binding type: ${wire}`);
  }
}

function bindingValueSource(header: string, bindingTypes: string[]): string {
  const parts = bindingTypes.map((wire) => ({ wire, ...bindingTypeParts(wire) }));

  const enumEntries = bindingTypes
    .map((wire) => `        ${wire.toUpperCase()}(${javaString(wire)})`)
    .join(",\n");

  const nullField = bindingTypes.includes("null")
    ? `    private static final BindingValue NULL_VALUE = new BindingValue(Type.NULL, 0L, 0.0, null, null);\n\n`
    : "";

  const factories = parts.map((p) => p.factory).join("\n\n");
  const accessors = parts
    .filter((p) => p.accessor !== undefined)
    .map((p) => p.accessor)
    .join("\n\n");

  // switch cases in bindingTypes order; adjacent cases with identical
  // bodies collapse into one fall-through group (INT32/INT64).
  const caseLines: string[] = [];
  for (let i = 0; i < parts.length; i++) {
    caseLines.push(`            case ${parts[i].wire.toUpperCase()}:`);
    if (i + 1 < parts.length && parts[i + 1].toStringBody === parts[i].toStringBody) {
      continue;
    }
    caseLines.push(`                ${parts[i].toStringBody}`);
  }
  caseLines.push("            default:");
  caseLines.push(`                return "BindingValue[" + type + "]";`);

  return `${header}
import java.util.Arrays;
import java.util.Objects;

/**
 * A typed binding value, discriminated by {@link Type}. Manual
 * discriminated class (Unity-2021-portable style, mirrored from the C#
 * {@code SqliteHostBindingValue}): a type enum, typed accessors that
 * throw on the wrong type, and static factories.
 */
public final class BindingValue {

    /** Envelope binding type discriminator (JSON {@code type} field). */
    public enum Type {
${enumEntries};

        private final String jsonName;

        Type(String jsonName) {
            this.jsonName = jsonName;
        }

        /** The wire name used in the JSON envelope (e.g. {@code "int64"}). */
        public String jsonName() {
            return jsonName;
        }

        /** Resolve a wire name; returns {@code null} for unknown names. */
        public static Type fromJsonName(String jsonName) {
            for (Type type : values()) {
                if (type.jsonName.equals(jsonName)) {
                    return type;
                }
            }
            return null;
        }
    }

${nullField}    private final Type type;
    private final long integerValue;
    private final double realValue;
    private final String textValue;
    private final byte[] blobValue;

    private BindingValue(
            Type type, long integerValue, double realValue, String textValue, byte[] blobValue) {
        this.type = type;
        this.integerValue = integerValue;
        this.realValue = realValue;
        this.textValue = textValue;
        this.blobValue = blobValue;
    }

${factories}

    /** The discriminator. */
    public Type type() {
        return type;
    }

${accessors}

    private void requireType(Type expected) {
        if (type != expected) {
            throw new IllegalStateException(
                    "binding value is of type " + type.jsonName()
                            + ", not " + expected.jsonName());
        }
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof BindingValue that)) {
            return false;
        }
        return type == that.type
                && integerValue == that.integerValue
                && Double.compare(realValue, that.realValue) == 0
                && Objects.equals(textValue, that.textValue)
                && Arrays.equals(blobValue, that.blobValue);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                type, integerValue, realValue, textValue, Arrays.hashCode(blobValue));
    }

    @Override
    public String toString() {
        switch (type) {
${caseLines.join("\n")}
        }
    }
}
`;
}

// ---------------------------------------------------------------------------
// Host method DTO records (<namespace-lowercased>.generated)
// ---------------------------------------------------------------------------

function generatedHeader(ir: HostLibraryIr, what: string): string {
  return `// <auto-generated />
// ${what} for the ${ir.library.namespace} host library (interface
// ${ir.library.interfaceName}, api level ${ir.library.apiLevel}). Emitted from the canonical
// manifest by @sqlite-host/emitter-java; regenerate instead of editing.
package ${generatedPackageName(ir)};
`;
}

function recordComponents(shape: ObjectShapeIr): string[] {
  const components = shape.fields.map(
    (f) => `${javaScalarType(f.scalarType, f.optional)} ${f.propertyName}`,
  );
  for (const list of shape.listFields) {
    components.push(`List<${list.itemModelName}> ${list.propertyName}`);
  }
  return components;
}

function renderRecordDeclaration(name: string, components: string[]): string {
  const oneLine = `public record ${name}(${components.join(", ")}) {`;
  if (oneLine.length <= MAX_LINE) {
    return oneLine;
  }
  return `public record ${name}(\n${components
    .map((c) => `        ${c}`)
    .join(",\n")}) {`;
}

function renderDtoRecord(
  header: string,
  javadoc: string,
  name: string,
  shape: ObjectShapeIr,
): string {
  const needsListImports = shape.listFields.length > 0;
  const imports = needsListImports
    ? "\nimport java.util.Collections;\nimport java.util.List;\n"
    : "";
  let body: string;
  if (shape.listFields.length === 0) {
    body = "\n}";
  } else {
    const assignments = shape.listFields
      .map(
        (list) => `        ${list.propertyName} = ${list.propertyName} == null
                ? Collections.emptyList()
                : List.copyOf(${list.propertyName});`,
      )
      .join("\n");
    body = `\n\n    public ${name} {\n${assignments}\n    }\n}`;
  }
  return `${header}${imports}
${javadoc}
${renderRecordDeclaration(name, recordComponents(shape))}${body}
`;
}

/** DTO records for every method input/result and their list item models,
 *  deduplicated by item model name (identical shapes required). */
export function emitHostMethodDtos(ir: HostLibraryIr): EmittedFile[] {
  const packageName = generatedPackageName(ir);
  const files: EmittedFile[] = [];
  const itemShapes = new Map<string, string>();

  const emitItems = (owner: string, listFields: ListFieldIr[]) => {
    for (const list of listFields) {
      const signature = JSON.stringify(list.itemFields);
      const existing = itemShapes.get(list.itemModelName);
      if (existing !== undefined) {
        if (existing !== signature) {
          throw new Error(
            `item model ${list.itemModelName} is used with conflicting shapes`,
          );
        }
        continue;
      }
      itemShapes.set(list.itemModelName, signature);
      const shape: ObjectShapeIr = {
        modelName: list.itemModelName,
        fields: list.itemFields,
        listFields: [],
      };
      const javadoc = `/**
 * List item model for {@code ${list.propertyName}} of {@code ${owner}}
 * (child table {@code ${list.childTable}}).
 */`;
      files.push({
        path: packagePath(packageName, list.itemModelName),
        contents: renderDtoRecord(
          generatedHeader(ir, "Host method DTO"),
          javadoc,
          list.itemModelName,
          shape,
        ),
      });
    }
  };

  for (const method of ir.methods) {
    const inputJavadoc = `/**
 * Input model for host method {@code ${method.methodName}}
 * (call table {@code ${method.callTable}}).
 */`;
    files.push({
      path: packagePath(packageName, method.input.modelName),
      contents: renderDtoRecord(
        generatedHeader(ir, "Host method DTO"),
        inputJavadoc,
        method.input.modelName,
        method.input,
      ),
    });
    emitItems(method.input.modelName, method.input.listFields);

    const resultJavadoc = `/**
 * Result model for host method {@code ${method.methodName}}
 * (result table {@code ${method.resultTable}}).
 */`;
    files.push({
      path: packagePath(packageName, method.result.modelName),
      contents: renderDtoRecord(
        generatedHeader(ir, "Host method DTO"),
        resultJavadoc,
        method.result.modelName,
        method.result,
      ),
    });
    emitItems(method.result.modelName, method.result.listFields);
  }
  return files;
}

// ---------------------------------------------------------------------------
// MethodDescriptors (compile-time manifest method metadata)
// ---------------------------------------------------------------------------

function stringListLiteral(values: string[]): string {
  return `List.of(${values.map(javaString).join(", ")})`;
}

function scalarColumns(fields: ScalarFieldIr[]): string[] {
  return fields.map((f) => f.column);
}

function methodConstantName(methodName: string): string {
  return toSnakeCase(methodName).toUpperCase();
}

/** Inline metadata literal: a nested Inline record, or null when absent. */
function inlineLiteral(method: HostMethodIr): string {
  if (method.inline === null) {
    return "null";
  }
  const { functionName, minArgs, maxArgs } = method.inline;
  return `new Inline(${javaString(functionName)}, ${minArgs}, ${maxArgs})`;
}

/** One MethodDescriptors class mirroring the manifest method metadata. */
export function emitMethodDescriptors(ir: HostLibraryIr): EmittedFile {
  const packageName = generatedPackageName(ir);
  const header = generatedHeader(ir, "Host method metadata");

  const constants = ir.methods
    .map((method) => {
      const args = [
        javaString(method.methodName),
        javaString(method.handlerName),
        String(method.apiLevel),
        javaString(method.callTable),
        javaString(method.resultTable),
        javaString(method.queueTrigger),
        stringListLiteral(scalarColumns(method.input.fields)),
        stringListLiteral(method.input.listFields.map((l) => l.childTable)),
        stringListLiteral(scalarColumns(method.result.fields)),
        stringListLiteral(method.result.listFields.map((l) => l.childTable)),
        inlineLiteral(method),
      ];
      return `    /** Metadata for host method {@code ${method.methodName}}. */
    public static final Method ${methodConstantName(method.methodName)} = new Method(
${args.map((a) => `            ${a}`).join(",\n")});`;
    })
    .join("\n\n");

  const allLiteral =
    ir.methods.length === 0
      ? "List.of();"
      : `List.of(\n${ir.methods
          .map((m) => `            ${methodConstantName(m.methodName)}`)
          .join(",\n")});`;

  const contents = `${header}
import java.util.List;

/**
 * Compile-time mirror of the manifest method metadata: resolved table,
 * trigger, and column names per host method, for host apps that want
 * the metadata without parsing manifest JSON.
 */
public final class MethodDescriptors {

    /** Engine identifier of the protocol this library targets. */
    public static final String ENGINE = ${javaString(ir.engine)};

    /** TypeSpec namespace of the host library. */
    public static final String NAMESPACE = ${javaString(ir.library.namespace)};

    /** Host method interface name. */
    public static final String INTERFACE_NAME = ${javaString(ir.library.interfaceName)};

    /** Api level of the host library. */
    public static final int API_LEVEL = ${ir.library.apiLevel};

    /** Minimum SQLite version required, in SQLITE_VERSION_NUMBER form. */
    public static final int MIN_SQLITE_VERSION_NUMBER = ${ir.library.minSqliteVersionNumber};

    /**
     * One host method's resolved manifest metadata. {@code inline} is
     * {@code null} for methods without an inline scalar function.
     */
    public record Method(
            String methodName,
            String handlerName,
            int apiLevel,
            String callTable,
            String resultTable,
            String queueTrigger,
            List<String> inputColumns,
            List<String> inputListTables,
            List<String> resultColumns,
            List<String> resultListTables,
            Inline inline) {
    }

    /** Inline scalar-function exposure of a method (feature inlineFunctions). */
    public record Inline(String functionName, int minArgs, int maxArgs) {
    }

${constants}

    /** All host methods in manifest order. */
    public static final List<Method> ALL = ${allLiteral}

    private MethodDescriptors() {
    }
}
`;
  return { path: packagePath(packageName, "MethodDescriptors"), contents };
}
