// <auto-generated />

using System.Collections.Generic;
using SqliteHost;

namespace Example.Game.Generated.Compact
{
    public static class GeneratedHostMethodSpecs
    {
        public static IReadOnlyList<IHostMethodSpec<IGeneratedHostHandlers>> BuildAll()
        {
            return new IHostMethodSpec<IGeneratedHostHandlers>[]
            {
                BuildGetValueSpec(),
                BuildSetValueSpec(),
                BuildGetValuesSpec(),
                BuildPutBlobSpec(),
                BuildRecordScoreSpec(),
            };
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildGetValueSpec()
        {
            return CompactHostMethod
                .For<IGeneratedHostHandlers>("getValue")
                .ApiLevel(1)
                .Tables("call_get_value", "result_get_value", "trg_call_get_value_queue")
                .CreateInput(CreateGetValueInput)
                .InputText("key", SetGetValueKey)
                .Column("input_key")
                .ResultLong("value", ReadGetValueValue)
                .Column("result_value")
                .Inline("fn_get_value", 1, 1)
                .Handler(InvokeGetValue)
                .Build();
        }

        private static object CreateGetValueInput()
        {
            return new GetValueInput();
        }

        private static void SetGetValueKey(object input, string value)
        {
            ((GetValueInput)input).Key = value;
        }

        private static long ReadGetValueValue(object result)
        {
            return ((GetValueResult)result).Value;
        }

        private static object InvokeGetValue(object handlers, object input)
        {
            return ((IGeneratedHostHandlers)handlers).GetValue((GetValueInput)input);
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildSetValueSpec()
        {
            return CompactHostMethod
                .For<IGeneratedHostHandlers>("setValue")
                .ApiLevel(1)
                .Tables("call_set_value", "result_set_value", "trg_call_set_value_queue")
                .CreateInput(CreateSetValueInput)
                .InputText("key", SetSetValueKey)
                .Column("input_key")
                .InputLong("value", SetSetValueValue)
                .Column("input_value")
                .ResultBool("success", ReadSetValueSuccess)
                .Column("result_success")
                .Handler(InvokeSetValue)
                .Build();
        }

        private static object CreateSetValueInput()
        {
            return new SetValueInput();
        }

        private static void SetSetValueKey(object input, string value)
        {
            ((SetValueInput)input).Key = value;
        }

        private static void SetSetValueValue(object input, long value)
        {
            ((SetValueInput)input).Value = value;
        }

        private static bool ReadSetValueSuccess(object result)
        {
            return ((SetValueResult)result).Success;
        }

        private static object InvokeSetValue(object handlers, object input)
        {
            return ((IGeneratedHostHandlers)handlers).SetValue((SetValueInput)input);
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildGetValuesSpec()
        {
            return CompactHostMethod
                .For<IGeneratedHostHandlers>("getValues")
                .ApiLevel(1)
                .Tables("call_get_values", "result_get_values", "trg_call_get_values_queue")
                .CreateInput(CreateGetValuesInput)
                .InputOptionalLong("default_value", SetGetValuesDefaultValue)
                .Column("input_default_value")
                .InputList("keys", CreateGetValuesKeysItem, AssignGetValuesKeys, ConfigureGetValuesKeysItem)
                .ChildTable("call_get_values__input_keys")
                .ResultList("entries", ReadGetValuesEntries, ConfigureGetValuesEntriesItem)
                .ChildTable("result_get_values__result_entries")
                .Handler(InvokeGetValues)
                .Build();
        }

        private static object CreateGetValuesInput()
        {
            return new GetValuesInput();
        }

        private static void SetGetValuesDefaultValue(object input, long? value)
        {
            ((GetValuesInput)input).DefaultValue = value;
        }

        private static object CreateGetValuesKeysItem()
        {
            return new KeyQueryItem();
        }

        private static void ConfigureGetValuesKeysItem(ICompactListItemFieldsBuilder item)
        {
            item
                .Text("key", SetKeyQueryItemKey)
                .Column("input_key");
        }

        private static void SetKeyQueryItemKey(object item, string value)
        {
            ((KeyQueryItem)item).Key = value;
        }

        private static void AssignGetValuesKeys(object input, IReadOnlyList<object> items)
        {
            var list = new List<KeyQueryItem>(items.Count);
            for (int i = 0; i < items.Count; i++)
            {
                list.Add((KeyQueryItem)items[i]);
            }
            ((GetValuesInput)input).Keys = list;
        }

        private static IReadOnlyList<object> ReadGetValuesEntries(object result)
        {
            List<ValueEntryItem> items = ((GetValuesResult)result).Entries;
            if (items == null)
            {
                return null;
            }
            var list = new List<object>(items.Count);
            for (int i = 0; i < items.Count; i++)
            {
                list.Add(items[i]);
            }
            return list;
        }

        private static void ConfigureGetValuesEntriesItem(ICompactListItemResultFieldsBuilder item)
        {
            item
                .Text("key", ReadValueEntryItemKey)
                .Column("result_key")
                .Long("value", ReadValueEntryItemValue)
                .Column("result_value")
                .Bool("found", ReadValueEntryItemFound)
                .Column("result_found");
        }

        private static string ReadValueEntryItemKey(object item)
        {
            return ((ValueEntryItem)item).Key;
        }

        private static long ReadValueEntryItemValue(object item)
        {
            return ((ValueEntryItem)item).Value;
        }

        private static bool ReadValueEntryItemFound(object item)
        {
            return ((ValueEntryItem)item).Found;
        }

        private static object InvokeGetValues(object handlers, object input)
        {
            return ((IGeneratedHostHandlers)handlers).GetValues((GetValuesInput)input);
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildPutBlobSpec()
        {
            return CompactHostMethod
                .For<IGeneratedHostHandlers>("putBlob")
                .ApiLevel(1)
                .Tables("call_put_blob", "result_put_blob", "trg_call_put_blob_queue")
                .CreateInput(CreatePutBlobInput)
                .InputText("key", SetPutBlobKey)
                .Column("input_key")
                .InputBlob("data", SetPutBlobData)
                .Column("input_data")
                .InputOptionalText("note", SetPutBlobNote)
                .Column("input_note")
                .ResultBool("stored", ReadPutBlobStored)
                .Column("result_stored")
                .Handler(InvokePutBlob)
                .Build();
        }

        private static object CreatePutBlobInput()
        {
            return new PutBlobInput();
        }

        private static void SetPutBlobKey(object input, string value)
        {
            ((PutBlobInput)input).Key = value;
        }

        private static void SetPutBlobData(object input, byte[] value)
        {
            ((PutBlobInput)input).Data = value;
        }

        private static void SetPutBlobNote(object input, string value)
        {
            ((PutBlobInput)input).Note = value;
        }

        private static bool ReadPutBlobStored(object result)
        {
            return ((PutBlobResult)result).Stored;
        }

        private static object InvokePutBlob(object handlers, object input)
        {
            return ((IGeneratedHostHandlers)handlers).PutBlob((PutBlobInput)input);
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildRecordScoreSpec()
        {
            return CompactHostMethod
                .For<IGeneratedHostHandlers>("recordScore")
                .ApiLevel(1)
                .Tables("call_record_score", "result_record_score", "trg_call_record_score_queue")
                .CreateInput(CreateRecordScoreInput)
                .InputText("key", SetRecordScoreKey)
                .Column("input_key")
                .InputDouble("score", SetRecordScoreScore)
                .Column("input_score")
                .InputOptionalFloat("weight", SetRecordScoreWeight)
                .Column("input_weight")
                .ResultDouble("average", ReadRecordScoreAverage)
                .Column("result_average")
                .Handler(InvokeRecordScore)
                .Build();
        }

        private static object CreateRecordScoreInput()
        {
            return new RecordScoreInput();
        }

        private static void SetRecordScoreKey(object input, string value)
        {
            ((RecordScoreInput)input).Key = value;
        }

        private static void SetRecordScoreScore(object input, double value)
        {
            ((RecordScoreInput)input).Score = value;
        }

        private static void SetRecordScoreWeight(object input, float? value)
        {
            ((RecordScoreInput)input).Weight = value;
        }

        private static double ReadRecordScoreAverage(object result)
        {
            return ((RecordScoreResult)result).Average;
        }

        private static object InvokeRecordScore(object handlers, object input)
        {
            return ((IGeneratedHostHandlers)handlers).RecordScore((RecordScoreInput)input);
        }
    }
}
