// <auto-generated />

using System.Collections.Generic;
using SqliteHost;

namespace Example.Game.Generated.Compact
{
    public static class GeneratedHostMethodSpecs
    {
        public static IReadOnlyList<IHostMethodSpec<IGeneratedHostHandlers>> BuildAll()
        {
            return new IHostMethodSpec<IGeneratedHostHandlers>[]
            {
                BuildGetValueSpec(),
                BuildSetValueSpec(),
                BuildGetValuesSpec(),
                BuildPutBlobSpec(),
                BuildRecordScoreSpec(),
            };
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildGetValueSpec()
        {
            return CompactHostMethod
                .For<IGeneratedHostHandlers>("getValue")
                .ApiLevel(1)
                .CreateInput(CreateGetValueInput)
                .InputText("key", SetGetValueKey)
                .ResultLong("value", ReadGetValueValue)
                .Inline("fn_get_value")
                .Handler(InvokeGetValue)
                .Build();
        }

        private static object CreateGetValueInput()
        {
            return new GetValueInput();
        }

        private static void SetGetValueKey(object input, string value)
        {
            ((GetValueInput)input).Key = value;
        }

        private static long ReadGetValueValue(object result)
        {
            return ((GetValueResult)result).Value;
        }

        private static object InvokeGetValue(object handlers, object input)
        {
            return ((IGeneratedHostHandlers)handlers).GetValue((GetValueInput)input);
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildSetValueSpec()
        {
            return CompactHostMethod
                .For<IGeneratedHostHandlers>("setValue")
                .ApiLevel(1)
                .CreateInput(CreateSetValueInput)
                .InputText("key", SetSetValueKey)
                .InputLong("value", SetSetValueValue)
                .ResultBool("success", ReadSetValueSuccess)
                .Handler(InvokeSetValue)
                .Build();
        }

        private static object CreateSetValueInput()
        {
            return new SetValueInput();
        }

        private static void SetSetValueKey(object input, string value)
        {
            ((SetValueInput)input).Key = value;
        }

        private static void SetSetValueValue(object input, long value)
        {
            ((SetValueInput)input).Value = value;
        }

        private static bool ReadSetValueSuccess(object result)
        {
            return ((SetValueResult)result).Success;
        }

        private static object InvokeSetValue(object handlers, object input)
        {
            return ((IGeneratedHostHandlers)handlers).SetValue((SetValueInput)input);
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildGetValuesSpec()
        {
            return CompactHostMethod
                .For<IGeneratedHostHandlers>("getValues")
                .ApiLevel(1)
                .CreateInput(CreateGetValuesInput)
                .InputOptionalLong("default_value", SetGetValuesDefaultValue)
                .InputList("keys", CreateGetValuesKeysItem, AssignGetValuesKeys, ConfigureGetValuesKeysItem)
                .ResultList("entries", ReadGetValuesEntries, ConfigureGetValuesEntriesItem)
                .Handler(InvokeGetValues)
                .Build();
        }

        private static object CreateGetValuesInput()
        {
            return new GetValuesInput();
        }

        private static void SetGetValuesDefaultValue(object input, long? value)
        {
            ((GetValuesInput)input).DefaultValue = value;
        }

        private static object CreateGetValuesKeysItem()
        {
            return new KeyQueryItem();
        }

        private static void ConfigureGetValuesKeysItem(ICompactListItemFieldsBuilder item)
        {
            item
                .Text("key", SetKeyQueryItemKey);
        }

        private static void SetKeyQueryItemKey(object item, string value)
        {
            ((KeyQueryItem)item).Key = value;
        }

        private static void AssignGetValuesKeys(object input, IReadOnlyList<object> items)
        {
            var list = new List<KeyQueryItem>(items.Count);
            for (int i = 0; i < items.Count; i++)
            {
                list.Add((KeyQueryItem)items[i]);
            }
            ((GetValuesInput)input).Keys = list;
        }

        private static IReadOnlyList<object> ReadGetValuesEntries(object result)
        {
            List<ValueEntryItem> items = ((GetValuesResult)result).Entries;
            if (items == null)
            {
                return null;
            }
            var list = new List<object>(items.Count);
            for (int i = 0; i < items.Count; i++)
            {
                list.Add(items[i]);
            }
            return list;
        }

        private static void ConfigureGetValuesEntriesItem(ICompactListItemResultFieldsBuilder item)
        {
            item
                .Text("key", ReadValueEntryItemKey)
                .Long("value", ReadValueEntryItemValue)
                .Bool("found", ReadValueEntryItemFound);
        }

        private static string ReadValueEntryItemKey(object item)
        {
            return ((ValueEntryItem)item).Key;
        }

        private static long ReadValueEntryItemValue(object item)
        {
            return ((ValueEntryItem)item).Value;
        }

        private static bool ReadValueEntryItemFound(object item)
        {
            return ((ValueEntryItem)item).Found;
        }

        private static object InvokeGetValues(object handlers, object input)
        {
            return ((IGeneratedHostHandlers)handlers).GetValues((GetValuesInput)input);
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildPutBlobSpec()
        {
            return CompactHostMethod
                .For<IGeneratedHostHandlers>("putBlob")
                .ApiLevel(1)
                .CreateInput(CreatePutBlobInput)
                .InputText("key", SetPutBlobKey)
                .InputBlob("data", SetPutBlobData)
                .InputOptionalText("note", SetPutBlobNote)
                .ResultBool("stored", ReadPutBlobStored)
                .Handler(InvokePutBlob)
                .Build();
        }

        private static object CreatePutBlobInput()
        {
            return new PutBlobInput();
        }

        private static void SetPutBlobKey(object input, string value)
        {
            ((PutBlobInput)input).Key = value;
        }

        private static void SetPutBlobData(object input, byte[] value)
        {
            ((PutBlobInput)input).Data = value;
        }

        private static void SetPutBlobNote(object input, string value)
        {
            ((PutBlobInput)input).Note = value;
        }

        private static bool ReadPutBlobStored(object result)
        {
            return ((PutBlobResult)result).Stored;
        }

        private static object InvokePutBlob(object handlers, object input)
        {
            return ((IGeneratedHostHandlers)handlers).PutBlob((PutBlobInput)input);
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildRecordScoreSpec()
        {
            return CompactHostMethod
                .For<IGeneratedHostHandlers>("recordScore")
                .ApiLevel(1)
                .CreateInput(CreateRecordScoreInput)
                .InputText("key", SetRecordScoreKey)
                .InputDouble("score", SetRecordScoreScore)
                .InputOptionalFloat("weight", SetRecordScoreWeight)
                .ResultDouble("average", ReadRecordScoreAverage)
                .Handler(InvokeRecordScore)
                .Build();
        }

        private static object CreateRecordScoreInput()
        {
            return new RecordScoreInput();
        }

        private static void SetRecordScoreKey(object input, string value)
        {
            ((RecordScoreInput)input).Key = value;
        }

        private static void SetRecordScoreScore(object input, double value)
        {
            ((RecordScoreInput)input).Score = value;
        }

        private static void SetRecordScoreWeight(object input, float? value)
        {
            ((RecordScoreInput)input).Weight = value;
        }

        private static double ReadRecordScoreAverage(object result)
        {
            return ((RecordScoreResult)result).Average;
        }

        private static object InvokeRecordScore(object handlers, object input)
        {
            return ((IGeneratedHostHandlers)handlers).RecordScore((RecordScoreInput)input);
        }
    }
}
