// <auto-generated />

namespace Example.Game.Generated.Compact
{
    public interface IGeneratedHostHandlers
    {
        GetValueResult GetValue(GetValueInput input);
        SetValueResult SetValue(SetValueInput input);
        GetValuesResult GetValues(GetValuesInput input);
        PutBlobResult PutBlob(PutBlobInput input);
        RecordScoreResult RecordScore(RecordScoreInput input);
    }
}
