// <auto-generated />

using System;
using System.Collections.Generic;

namespace SqliteHost
{
    /// <summary>
    /// Protocol constants projected from codegen/core/src/ir.ts
    /// (docs/proposals/rule-parameters-as-data.md). Do not edit by hand —
    /// regenerate via the C# emitter; the cross-language golden pins this.
    /// </summary>
    internal static class ProtocolConstants
    {
        /// <summary>
        /// Reserved initial queue status (ir.ts PENDING_STATUS). The queue
        /// DDL defaults new rows to this literal and the runtime drain
        /// selects rows with this status; a doneValue equal to it would
        /// leave drained rows selectable, so it is rejected at registration.
        /// </summary>
        internal const string PendingStatus = "pending";

#if !SQLITEHOST_SLIM
        /// <summary>
        /// SQLite built-in function names an inline function name must not
        /// collide with (ir.ts SQLITE_BUILTIN_FUNCTIONS). SQLite resolves
        /// function names case-insensitively, so membership ignores case.
        /// </summary>
        internal static readonly HashSet<string> SqliteBuiltinFunctions =
            new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "abs",
                "coalesce",
                "count",
                "sum",
                "min",
                "max",
                "length",
                "lower",
                "upper",
                "printf",
                "random",
                "replace",
                "round",
                "substr",
                "trim",
                "date",
                "time",
                "datetime",
                "ifnull",
                "nullif",
                "instr",
                "hex",
                "quote",
                "total",
                "group_concat",
                "typeof",
                "unicode",
                "char",
                "likelihood",
                "likely",
                "unlikely",
                "last_insert_rowid",
                "changes",
                "sqlite_version",
                "glob",
                "like",
                "zeroblob"
            };
#endif
    }
}
