// <auto-generated />

using SqliteHost;

namespace Example.Game.Generated
{
    public static class GeneratedHostDefinition
    {
        public static SqliteHostDefinition<IGeneratedHostHandlers> Build()
        {
            return SqliteHostDefinition
                .ForHandlers<IGeneratedHostHandlers>()
                .ApiLevel(1)
                .MinSqliteVersion(3019003)
                .Naming(n => n
                    .CallTablePrefix("call_")
                    .ResultTablePrefix("result_")
                    .InputColumnPrefix("input_")
                    .ResultColumnPrefix("result_")
                    .InputListTableInfix("__input_")
                    .ResultListTableInfix("__result_")
                    .QueueTable("pending_host_calls")
                    .InputsTable("script_inputs")
                    .VarsTable("script_vars")
                    .ControlTable("script_control")
                    .FunctionPrefix("fn_"))
                .Columns(c => c
                    .CallId("call_id")
                    .ItemIndex("item_index")
                    .Status("status")
                    .DoneValue("done")
                    .QueueId("queue_id")
                    .Method("method")
                    .Name("name")
                    .ValueType("value_type")
                    .IntValue("int_value")
                    .RealValue("real_value")
                    .TextValue("text_value")
                    .BlobValue("blob_value")
                    .Action("action")
                    .Message("message"))
                .Methods(GeneratedHostMethodSpecs.BuildAll());
        }
    }
}
