// <auto-generated />

using System.Collections.Generic;
using SqliteHost;

namespace Example.Game.Generated
{
    public static class GeneratedHostMethodSpecs
    {
        public static IReadOnlyList<IHostMethodSpec<IGeneratedHostHandlers>> BuildAll()
        {
            return new IHostMethodSpec<IGeneratedHostHandlers>[]
            {
                BuildGetValueSpec(),
                BuildSetValueSpec(),
                BuildGetValuesSpec(),
                BuildPutBlobSpec(),
                BuildRecordScoreSpec(),
            };
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildGetValueSpec()
        {
            return HostMethod
                .For<IGeneratedHostHandlers, GetValueInput, GetValueResult>("getValue")
                .ApiLevel(1)
                .Inputs(i => i
                    .Text("key", (x, v) => x.Key = v))
                .Results(r => r
                    .Long("value", x => x.Value))
                .Inline("fn_get_value")
                .Handler((handlers, input) => handlers.GetValue(input))
                .Build();
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildSetValueSpec()
        {
            return HostMethod
                .For<IGeneratedHostHandlers, SetValueInput, SetValueResult>("setValue")
                .ApiLevel(1)
                .Inputs(i => i
                    .Text("key", (x, v) => x.Key = v)
                    .Long("value", (x, v) => x.Value = v))
                .Results(r => r
                    .Bool("success", x => x.Success))
                .Handler((handlers, input) => handlers.SetValue(input))
                .Build();
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildGetValuesSpec()
        {
            return HostMethod
                .For<IGeneratedHostHandlers, GetValuesInput, GetValuesResult>("getValues")
                .ApiLevel(1)
                .Inputs(i => i
                    .OptionalLong("default_value", (x, v) => x.DefaultValue = v)
                    .List<KeyQueryItem>("keys", (x, v) => x.Keys = v, item => item
                        .Text("key", (x, v) => x.Key = v)))
                .Results(r => r
                    .List<ValueEntryItem>("entries", x => x.Entries, item => item
                        .Text("key", x => x.Key)
                        .Long("value", x => x.Value)
                        .Bool("found", x => x.Found)))
                .Handler((handlers, input) => handlers.GetValues(input))
                .Build();
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildPutBlobSpec()
        {
            return HostMethod
                .For<IGeneratedHostHandlers, PutBlobInput, PutBlobResult>("putBlob")
                .ApiLevel(1)
                .Inputs(i => i
                    .Text("key", (x, v) => x.Key = v)
                    .Blob("data", (x, v) => x.Data = v)
                    .OptionalText("note", (x, v) => x.Note = v))
                .Results(r => r
                    .Bool("stored", x => x.Stored))
                .Handler((handlers, input) => handlers.PutBlob(input))
                .Build();
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildRecordScoreSpec()
        {
            return HostMethod
                .For<IGeneratedHostHandlers, RecordScoreInput, RecordScoreResult>("recordScore")
                .ApiLevel(1)
                .Inputs(i => i
                    .Text("key", (x, v) => x.Key = v)
                    .Double("score", (x, v) => x.Score = v)
                    .OptionalFloat("weight", (x, v) => x.Weight = v))
                .Results(r => r
                    .Double("average", x => x.Average))
                .Handler((handlers, input) => handlers.RecordScore(input))
                .Build();
        }
    }
}
