// <auto-generated />

using System.Collections.Generic;

namespace Example.Game.Generated
{
    public class GetValueInput
    {
        public string Key { get; set; }
    }

    public class GetValueResult
    {
        public long Value { get; set; }
    }

    public class SetValueInput
    {
        public string Key { get; set; }
        public long Value { get; set; }
    }

    public class SetValueResult
    {
        public bool Success { get; set; }
    }

    public class GetValuesInput
    {
        public long? DefaultValue { get; set; }
        public List<KeyQueryItem> Keys { get; set; } = new List<KeyQueryItem>();
    }

    public class KeyQueryItem
    {
        public string Key { get; set; }
    }

    public class GetValuesResult
    {
        public List<ValueEntryItem> Entries { get; set; } = new List<ValueEntryItem>();
    }

    public class ValueEntryItem
    {
        public string Key { get; set; }
        public long Value { get; set; }
        public bool Found { get; set; }
    }

    public class PutBlobInput
    {
        public string Key { get; set; }
        public byte[] Data { get; set; }
        public string Note { get; set; }
    }

    public class PutBlobResult
    {
        public bool Stored { get; set; }
    }

    public class RecordScoreInput
    {
        public string Key { get; set; }
        public double Score { get; set; }
        public float? Weight { get; set; }
    }

    public class RecordScoreResult
    {
        public double Average { get; set; }
    }
}
