// <auto-generated />
// Generated-style projection of the SqliteHost script envelope
// (typespec/library, protocol sqlite-host-v1). Kept in sync with the
// cross-language contract (docs/script-envelope.md) by golden tests;
// do not edit independently of that contract.
package io.sqlitehost.model.envelope;

import java.util.Arrays;
import java.util.Objects;

/**
 * A typed binding value, discriminated by {@link Type}. Manual
 * discriminated class (Unity-2021-portable style, mirrored from the C#
 * {@code SqliteHostBindingValue}): a type enum, typed accessors that
 * throw on the wrong type, and static factories.
 */
public final class BindingValue {

    /** Envelope binding type discriminator (JSON {@code type} field). */
    public enum Type {
        NULL("null"),
        INT32("int32"),
        INT64("int64"),
        BOOL("bool"),
        TEXT("text"),
        BLOB("blob"),
        FLOAT32("float32"),
        FLOAT64("float64");

        private final String jsonName;

        Type(String jsonName) {
            this.jsonName = jsonName;
        }

        /** The wire name used in the JSON envelope (e.g. {@code "int64"}). */
        public String jsonName() {
            return jsonName;
        }

        /** Resolve a wire name; returns {@code null} for unknown names. */
        public static Type fromJsonName(String jsonName) {
            for (Type type : values()) {
                if (type.jsonName.equals(jsonName)) {
                    return type;
                }
            }
            return null;
        }
    }

    private static final BindingValue NULL_VALUE = new BindingValue(Type.NULL, 0L, 0.0, null, null);

    private final Type type;
    private final long integerValue;
    private final double realValue;
    private final String textValue;
    private final byte[] blobValue;

    private BindingValue(
            Type type, long integerValue, double realValue, String textValue, byte[] blobValue) {
        this.type = type;
        this.integerValue = integerValue;
        this.realValue = realValue;
        this.textValue = textValue;
        this.blobValue = blobValue;
    }

    /** The {@code null} binding value. */
    public static BindingValue nullValue() {
        return NULL_VALUE;
    }

    /** An {@code int32} binding value. */
    public static BindingValue int32(int value) {
        return new BindingValue(Type.INT32, value, 0.0, null, null);
    }

    /** An {@code int64} binding value. */
    public static BindingValue int64(long value) {
        return new BindingValue(Type.INT64, value, 0.0, null, null);
    }

    /** A {@code bool} binding value. */
    public static BindingValue bool(boolean value) {
        return new BindingValue(Type.BOOL, value ? 1L : 0L, 0.0, null, null);
    }

    /** A {@code text} binding value. */
    public static BindingValue text(String value) {
        Objects.requireNonNull(value, "value");
        return new BindingValue(Type.TEXT, 0L, 0.0, value, null);
    }

    /** A {@code blob} binding value (the byte array is copied). */
    public static BindingValue blob(byte[] value) {
        Objects.requireNonNull(value, "value");
        return new BindingValue(Type.BLOB, 0L, 0.0, null, value.clone());
    }

    /** A {@code float32} binding value. */
    public static BindingValue float32(float value) {
        return new BindingValue(Type.FLOAT32, 0L, value, null, null);
    }

    /** A {@code float64} binding value. */
    public static BindingValue float64(double value) {
        return new BindingValue(Type.FLOAT64, 0L, value, null, null);
    }

    /** The discriminator. */
    public Type type() {
        return type;
    }

    /** @throws IllegalStateException when {@link #type()} is not {@code INT32} */
    public int asInt32() {
        requireType(Type.INT32);
        return (int) integerValue;
    }

    /** @throws IllegalStateException when {@link #type()} is not {@code INT64} */
    public long asInt64() {
        requireType(Type.INT64);
        return integerValue;
    }

    /** @throws IllegalStateException when {@link #type()} is not {@code BOOL} */
    public boolean asBool() {
        requireType(Type.BOOL);
        return integerValue != 0L;
    }

    /** @throws IllegalStateException when {@link #type()} is not {@code TEXT} */
    public String asText() {
        requireType(Type.TEXT);
        return textValue;
    }

    /**
     * A copy of the blob bytes.
     *
     * @throws IllegalStateException when {@link #type()} is not {@code BLOB}
     */
    public byte[] asBlob() {
        requireType(Type.BLOB);
        return blobValue.clone();
    }

    /** @throws IllegalStateException when {@link #type()} is not {@code FLOAT32} */
    public float asFloat32() {
        requireType(Type.FLOAT32);
        return (float) realValue;
    }

    /** @throws IllegalStateException when {@link #type()} is not {@code FLOAT64} */
    public double asFloat64() {
        requireType(Type.FLOAT64);
        return realValue;
    }

    private void requireType(Type expected) {
        if (type != expected) {
            throw new IllegalStateException(
                    "binding value is of type " + type.jsonName()
                            + ", not " + expected.jsonName());
        }
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof BindingValue that)) {
            return false;
        }
        return type == that.type
                && integerValue == that.integerValue
                && Double.compare(realValue, that.realValue) == 0
                && Objects.equals(textValue, that.textValue)
                && Arrays.equals(blobValue, that.blobValue);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                type, integerValue, realValue, textValue, Arrays.hashCode(blobValue));
    }

    @Override
    public String toString() {
        switch (type) {
            case NULL:
                return "BindingValue[null]";
            case INT32:
            case INT64:
                return "BindingValue[" + type.jsonName() + " " + integerValue + "]";
            case BOOL:
                return "BindingValue[bool " + (integerValue != 0L) + "]";
            case TEXT:
                return "BindingValue[text " + textValue + "]";
            case BLOB:
                return "BindingValue[blob " + blobValue.length + " bytes]";
            case FLOAT32:
            case FLOAT64:
                return "BindingValue[" + type.jsonName() + " " + realValue + "]";
            default:
                return "BindingValue[" + type + "]";
        }
    }
}
