// <auto-generated />
// Generated-style projection of the SqliteHost script envelope
// (typespec/library, protocol sqlite-host-v1). Kept in sync with the
// cross-language contract (docs/script-envelope.md) by golden tests;
// do not edit independently of that contract.
package io.sqlitehost.model.envelope;

/**
 * A runtime input inserted into the {@code script_inputs} table before
 * the first step runs.
 */
public record RuntimeInput(String name, BindingValue value) {
}
