// <auto-generated />
// Generated-style projection of the SqliteHost script envelope
// (typespec/library, protocol sqlite-host-v1). Kept in sync with the
// cross-language contract (docs/script-envelope.md) by golden tests;
// do not edit independently of that contract.
package io.sqlitehost.model.envelope;

import java.util.Collections;
import java.util.List;

/**
 * The parsed script envelope (protocol v1). Field semantics follow
 * docs/script-envelope.md; fields that are optional on the wire are
 * empty lists (or {@code null} for scalars) when absent. Structural
 * validity is the validator's job, not this model's.
 */
public record Script(
        String engine,
        String scriptId,
        Integer requiredApiLevel,
        List<String> requiredFeatures,
        List<String> requiredMethods,
        List<RuntimeInput> inputs,
        List<Step> steps) {

    /** The only engine value understood by protocol v1. */
    public static final String ENGINE_V1 = "sqlite-host-v1";

    public Script {
        requiredFeatures = copyOrEmpty(requiredFeatures);
        requiredMethods = copyOrEmpty(requiredMethods);
        inputs = copyOrEmpty(inputs);
        steps = copyOrEmpty(steps);
    }

    private static <T> List<T> copyOrEmpty(List<T> list) {
        return list == null ? Collections.emptyList() : List.copyOf(list);
    }
}
