// <auto-generated />
// Generated-style projection of the SqliteHost script envelope
// (typespec/library, protocol sqlite-host-v1). Kept in sync with the
// cross-language contract (docs/script-envelope.md) by golden tests;
// do not edit independently of that contract.
package io.sqlitehost.model.envelope;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * One SQL statement of a step: the SQL text plus its named bindings
 * (bare names, no {@code :}/{@code @}/{@code $} prefix).
 */
public record Statement(String sql, Map<String, BindingValue> bindings) {

    public Statement {
        bindings = bindings == null
                ? Collections.emptyMap()
                : Collections.unmodifiableMap(new LinkedHashMap<>(bindings));
    }
}
