// <auto-generated />
// Generated-style projection of the SqliteHost script envelope
// (typespec/library, protocol sqlite-host-v1). Kept in sync with the
// cross-language contract (docs/script-envelope.md) by golden tests;
// do not edit independently of that contract.
package io.sqlitehost.model.envelope;

import java.util.Collections;
import java.util.List;

/**
 * One ordered script step. Statements run in order within the step;
 * the runtime drains pending host calls only after all statements of
 * the step succeeded.
 */
public record Step(String id, List<Statement> statements) {

    public Step {
        statements = statements == null
                ? Collections.emptyList()
                : List.copyOf(statements);
    }
}
