// <auto-generated />

using System.Collections.Generic;

namespace SqliteHost
{
    public class SqliteHostScript
    {
        public string Engine { get; set; }
        public string ScriptId { get; set; }
        public int RequiredApiLevel { get; set; }
        public List<string> RequiredFeatures { get; set; }
        public List<string> RequiredMethods { get; set; }
        public List<SqliteHostRuntimeInput> Inputs { get; set; }
        public List<SqliteHostStep> Steps { get; set; }
    }

    public class SqliteHostRuntimeInput
    {
        public string Name { get; set; }
        public SqliteHostBindingValue Value { get; set; }
    }

    public class SqliteHostStep
    {
        public string Id { get; set; }
        public List<SqliteHostStatement> Statements { get; set; }
    }

    public class SqliteHostStatement
    {
        public string Sql { get; set; }
        public Dictionary<string, SqliteHostBindingValue> Bindings { get; set; }
    }
}
