// <auto-generated />

using SqliteHost;

namespace Example.Game.Generated
{
    public static class GeneratedHostDefinition
    {
        public static SqliteHostDefinition<IGeneratedHostHandlers> Build()
        {
            return SqliteHostDefinition
                .ForHandlers<IGeneratedHostHandlers>()
                .ApiLevel(1)
                .MinSqliteVersion(3019003)
                .Naming(n => n
                    .CallTablePrefix("call_")
                    .ResultTablePrefix("result_")
                    .InputColumnPrefix("input_")
                    .ResultColumnPrefix("result_")
                    .InputListTableInfix("__input_")
                    .ResultListTableInfix("__result_"))
                .Methods(GeneratedHostMethodSpecs.BuildAll());
        }
    }
}
