// <auto-generated />

using System.Collections.Generic;
using SqliteHost;

namespace Example.Game.Generated.Ultra
{
    public static class GeneratedHostMethodSpecs
    {
        public static IReadOnlyList<IHostMethodSpec<IGeneratedHostHandlers>> BuildAll()
        {
            return new IHostMethodSpec<IGeneratedHostHandlers>[]
            {
                BuildGetValueSpec(),
                BuildSetValueSpec(),
                BuildGetValuesSpec(),
                BuildPutBlobSpec(),
                BuildRecordScoreSpec(),
            };
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildGetValueSpec()
        {
            return UltraHostMethod
                .For<IGeneratedHostHandlers>("getValue")
                .ApiLevel(1)
                .InputText("key")
                .ResultLong("value")
                .Inline("fn_get_value")
                .Handler(InvokeGetValue)
                .Build();
        }

        private static SqliteHostUltraResult InvokeGetValue(object handlers, SqliteHostUltraCall call)
        {
            return ((IGeneratedHostHandlers)handlers).GetValue(call);
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildSetValueSpec()
        {
            return UltraHostMethod
                .For<IGeneratedHostHandlers>("setValue")
                .ApiLevel(1)
                .InputText("key")
                .InputLong("value")
                .ResultBool("success")
                .Handler(InvokeSetValue)
                .Build();
        }

        private static SqliteHostUltraResult InvokeSetValue(object handlers, SqliteHostUltraCall call)
        {
            return ((IGeneratedHostHandlers)handlers).SetValue(call);
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildGetValuesSpec()
        {
            return UltraHostMethod
                .For<IGeneratedHostHandlers>("getValues")
                .ApiLevel(1)
                .InputOptionalLong("default_value")
                .InputList("keys", ConfigureGetValuesKeysItem)
                .ResultList("entries", ConfigureGetValuesEntriesItem)
                .Handler(InvokeGetValues)
                .Build();
        }

        private static void ConfigureGetValuesKeysItem(IUltraListItemFieldsBuilder item)
        {
            item
                .Text("key");
        }

        private static void ConfigureGetValuesEntriesItem(IUltraListItemFieldsBuilder item)
        {
            item
                .Text("key")
                .Long("value")
                .Bool("found");
        }

        private static SqliteHostUltraResult InvokeGetValues(object handlers, SqliteHostUltraCall call)
        {
            return ((IGeneratedHostHandlers)handlers).GetValues(call);
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildPutBlobSpec()
        {
            return UltraHostMethod
                .For<IGeneratedHostHandlers>("putBlob")
                .ApiLevel(1)
                .InputText("key")
                .InputBlob("data")
                .InputOptionalText("note")
                .ResultBool("stored")
                .Handler(InvokePutBlob)
                .Build();
        }

        private static SqliteHostUltraResult InvokePutBlob(object handlers, SqliteHostUltraCall call)
        {
            return ((IGeneratedHostHandlers)handlers).PutBlob(call);
        }

        private static IHostMethodSpec<IGeneratedHostHandlers> BuildRecordScoreSpec()
        {
            return UltraHostMethod
                .For<IGeneratedHostHandlers>("recordScore")
                .ApiLevel(1)
                .InputText("key")
                .InputDouble("score")
                .InputOptionalFloat("weight")
                .ResultDouble("average")
                .Handler(InvokeRecordScore)
                .Build();
        }

        private static SqliteHostUltraResult InvokeRecordScore(object handlers, SqliteHostUltraCall call)
        {
            return ((IGeneratedHostHandlers)handlers).RecordScore(call);
        }
    }
}
