// <auto-generated />

using SqliteHost;

namespace Example.Game.Generated.Ultra
{
    public interface IGeneratedHostHandlers
    {
        SqliteHostUltraResult GetValue(SqliteHostUltraCall call);
        SqliteHostUltraResult SetValue(SqliteHostUltraCall call);
        SqliteHostUltraResult GetValues(SqliteHostUltraCall call);
        SqliteHostUltraResult PutBlob(SqliteHostUltraCall call);
        SqliteHostUltraResult RecordScore(SqliteHostUltraCall call);
    }
}
