// <auto-generated />
// Protocol constants projected from codegen/core/src/ir.ts (protocol
// sqlite-host-v1, docs/proposals/rule-parameters-as-data.md). Kept in sync
// with the cross-language contract by golden tests; do not edit by hand.
package io.sqlitehost.model;

import java.util.Map;
import java.util.Set;

/**
 * Host-independent protocol constants shared across the language ports,
 * projected from the single source in {@code codegen/core/src/ir.ts}.
 */
public final class Protocol {

    /**
     * Reserved initial queue status ({@code ir.ts PENDING_STATUS}): the queue
     * DDL defaults new rows to this literal and the runtime drain selects
     * rows with this status.
     */
    public static final String PENDING_STATUS = "pending";

    /**
     * Feature flag ({@code ir.ts FEATURE_INLINE_FUNCTIONS}) a script must
     * declare in {@code requiredFeatures} to call a host's inline functions;
     * the validator gates inline-function use on its presence.
     */
    public static final String FEATURE_INLINE_FUNCTIONS = "inlineFunctions";

    /**
     * Binding-type compatibility ({@code ir.ts BINDING_TYPE_COMPAT}): for each
     * scalar column type (manifest wire name), the envelope binding value
     * types that may feed it. A {@code null} binding is accepted iff the
     * column is optional — that rule stays with the caller.
     */
    public static final Map<String, Set<String>> BINDING_TYPE_COMPAT = Map.of(
            "int32", Set.of("int32"),
            "int64", Set.of("int32", "int64"),
            "boolean", Set.of("bool"),
            "string", Set.of("text"),
            "bytes", Set.of("blob"),
            "float32", Set.of("float32"),
            "float64", Set.of("float32", "float64"));

    /**
     * Built-ins that return a different value on every evaluation
     * ({@code ir.ts NONDETERMINISTIC_FUNCTIONS_ALWAYS}): every call is
     * flagged by the determinism lint, whatever its arguments.
     */
    public static final Set<String> NONDETERMINISTIC_FUNCTIONS_ALWAYS =
            Set.of("random", "randomblob");

    /**
     * Date/time built-ins ({@code ir.ts NONDETERMINISTIC_TIME_FUNCTIONS})
     * that are nondeterministic only when they read the wall clock — called
     * with no arguments, or with the time value {@code 'now'}.
     */
    public static final Set<String> NONDETERMINISTIC_TIME_FUNCTIONS =
            Set.of("date", "time", "datetime", "julianday", "strftime");

    private Protocol() {
    }
}
