// <auto-generated />
// Protocol constants projected from codegen/core/src/ir.ts (protocol
// sqlite-host-v1, docs/proposals/rule-parameters-as-data.md). Kept in sync
// with the cross-language contract by golden tests; do not edit by hand.
package io.sqlitehost.model;

import java.util.Map;
import java.util.Set;

/**
 * Host-independent protocol constants shared across the language ports,
 * projected from the single source in {@code codegen/core/src/ir.ts}.
 */
public final class Protocol {

    /**
     * Reserved initial queue status ({@code ir.ts PENDING_STATUS}): the queue
     * DDL defaults new rows to this literal and the runtime drain selects
     * rows with this status.
     */
    public static final String PENDING_STATUS = "pending";

    /**
     * Feature flag ({@code ir.ts FEATURE_INLINE_FUNCTIONS}) a script must
     * declare in {@code requiredFeatures} to call a host's inline functions;
     * the validator gates inline-function use on its presence.
     */
    public static final String FEATURE_INLINE_FUNCTIONS = "inlineFunctions";

    /**
     * Binding-type compatibility ({@code ir.ts BINDING_TYPE_COMPAT}): for each
     * scalar column type (manifest wire name), the envelope binding value
     * types that may feed it. A {@code null} binding is accepted iff the
     * column is optional — that rule stays with the caller.
     */
    public static final Map<String, Set<String>> BINDING_TYPE_COMPAT = Map.of(
            "int32", Set.of("int32"),
            "int64", Set.of("int32", "int64"),
            "boolean", Set.of("bool"),
            "string", Set.of("text"),
            "bytes", Set.of("blob"),
            "float32", Set.of("float32"),
            "float64", Set.of("float32", "float64"));

    /**
     * Built-ins that return a different value on every evaluation
     * ({@code ir.ts NONDETERMINISTIC_FUNCTIONS_ALWAYS}): every call is
     * flagged by the determinism lint, whatever its arguments.
     */
    public static final Set<String> NONDETERMINISTIC_FUNCTIONS_ALWAYS =
            Set.of("random", "randomblob");

    /**
     * Date/time built-ins ({@code ir.ts NONDETERMINISTIC_TIME_FUNCTIONS})
     * that are nondeterministic only when they read the wall clock — called
     * with no arguments, or with the time value {@code 'now'}.
     */
    public static final Set<String> NONDETERMINISTIC_TIME_FUNCTIONS =
            Set.of("date", "time", "datetime", "julianday", "strftime");

    /**
     * SQLite built-ins introduced above the default floor
     * ({@code ir.ts FUNCTION_MIN_VERSION}), keyed by the SQLITE_VERSION_NUMBER
     * of the release that added them. The validator compares each entry
     * against the host manifest's {@code library.minSqliteVersionNumber}.
     */
    public static final Map<String, Integer> FUNCTION_MIN_VERSION = Map.ofEntries(
            Map.entry("row_number", 3025000),
            Map.entry("rank", 3025000),
            Map.entry("dense_rank", 3025000),
            Map.entry("percent_rank", 3025000),
            Map.entry("cume_dist", 3025000),
            Map.entry("ntile", 3025000),
            Map.entry("lag", 3025000),
            Map.entry("lead", 3025000),
            Map.entry("first_value", 3025000),
            Map.entry("last_value", 3025000),
            Map.entry("nth_value", 3025000),
            Map.entry("iif", 3032000),
            Map.entry("format", 3038000),
            Map.entry("unixepoch", 3038000),
            Map.entry("octet_length", 3043000),
            Map.entry("timediff", 3043000),
            Map.entry("concat", 3044000),
            Map.entry("concat_ws", 3044000),
            Map.entry("string_agg", 3044000));

    /**
     * Version floors for whole function families, keyed by name prefix
     * ({@code ir.ts FUNCTION_PREFIX_MIN_VERSION}) — the LONGEST matching
     * prefix wins. Covers the JSON surface, too large to enumerate by hand.
     */
    public static final Map<String, Integer> FUNCTION_PREFIX_MIN_VERSION = Map.of(
            "json", 3038000,
            "jsonb", 3045000);

    /**
     * Built-ins whose presence is decided by the device engine's compile
     * options rather than its version ({@code ir.ts NONPORTABLE_FUNCTIONS}),
     * so no version floor can make them safe.
     */
    public static final Set<String> NONPORTABLE_FUNCTIONS = Set.of(
            "acos", "acosh", "asin", "asinh", "atan", "atan2", "atanh", "ceil",
            "ceiling", "cos", "cosh", "degrees", "exp", "floor", "ln", "log",
            "log10", "log2", "mod", "pi", "pow", "power", "radians", "sin",
            "sinh", "sqrt", "tan", "tanh", "trunc");

    /**
     * Statement kinds a script may not use, matched on the statement's first
     * meaningful token ({@code ir.ts FORBIDDEN_LEADING_KEYWORDS}).
     */
    public static final Set<String> FORBIDDEN_LEADING_KEYWORDS = Set.of(
            "alter", "analyze", "attach", "begin", "commit", "create", "detach",
            "drop", "end", "pragma", "reindex", "release", "rollback",
            "savepoint", "vacuum");

    private Protocol() {
    }
}
