// <auto-generated />
// Protocol constants projected from codegen/core/src/ir.ts (protocol
// sqlite-host-v1, docs/proposals/rule-parameters-as-data.md). Kept in sync
// with the cross-language contract by golden tests; do not edit by hand.
package io.sqlitehost.model;

import java.util.Map;
import java.util.Set;

/**
 * Host-independent protocol constants shared across the language ports,
 * projected from the single source in {@code codegen/core/src/ir.ts}.
 */
public final class Protocol {

    /**
     * Reserved initial queue status ({@code ir.ts PENDING_STATUS}): the queue
     * DDL defaults new rows to this literal and the runtime drain selects
     * rows with this status.
     */
    public static final String PENDING_STATUS = "pending";

    /**
     * Feature flag ({@code ir.ts FEATURE_INLINE_FUNCTIONS}) a script must
     * declare in {@code requiredFeatures} to call a host's inline functions;
     * the validator gates inline-function use on its presence.
     */
    public static final String FEATURE_INLINE_FUNCTIONS = "inlineFunctions";

    /**
     * Binding-type compatibility ({@code ir.ts BINDING_TYPE_COMPAT}): for each
     * scalar column type (manifest wire name), the envelope binding value
     * types that may feed it. A {@code null} binding is accepted iff the
     * column is optional — that rule stays with the caller.
     */
    public static final Map<String, Set<String>> BINDING_TYPE_COMPAT = Map.of(
            "int32", Set.of("int32"),
            "int64", Set.of("int32", "int64"),
            "boolean", Set.of("bool"),
            "string", Set.of("text"),
            "bytes", Set.of("blob"),
            "float32", Set.of("float32"),
            "float64", Set.of("float32", "float64"));

    /**
     * Built-ins that return a different value on every evaluation
     * ({@code ir.ts NONDETERMINISTIC_FUNCTIONS_ALWAYS}): every call is
     * flagged by the determinism lint, whatever its arguments.
     */
    public static final Set<String> NONDETERMINISTIC_FUNCTIONS_ALWAYS =
            Set.of("random", "randomblob");

    /**
     * Date/time built-ins ({@code ir.ts NONDETERMINISTIC_TIME_FUNCTIONS})
     * that are nondeterministic only when they read the wall clock — called
     * with no arguments, or with the time value {@code 'now'}.
     */
    public static final Set<String> NONDETERMINISTIC_TIME_FUNCTIONS =
            Set.of("date", "time", "datetime", "julianday", "strftime");

    /**
     * The wall-clock KEYWORDS ({@code ir.ts NONDETERMINISTIC_TIME_KEYWORDS}).
     * SQLite spells these with no argument list, so a scan over parsed
     * function calls never sees them; they are matched against bare
     * identifier tokens instead, lowercased.
     */
    public static final Set<String> NONDETERMINISTIC_TIME_KEYWORDS =
            Set.of("current_timestamp", "current_date", "current_time");

    /**
     * SQLite built-ins introduced above the default floor
     * ({@code ir.ts FUNCTION_MIN_VERSION}), keyed by the SQLITE_VERSION_NUMBER
     * of the release that added them. The validator compares each entry
     * against the host manifest's {@code library.minSqliteVersionNumber}.
     */
    public static final Map<String, Integer> FUNCTION_MIN_VERSION = Map.ofEntries(
            Map.entry("row_number", 3025000),
            Map.entry("rank", 3025000),
            Map.entry("dense_rank", 3025000),
            Map.entry("percent_rank", 3025000),
            Map.entry("cume_dist", 3025000),
            Map.entry("ntile", 3025000),
            Map.entry("lag", 3025000),
            Map.entry("lead", 3025000),
            Map.entry("first_value", 3025000),
            Map.entry("last_value", 3025000),
            Map.entry("nth_value", 3025000),
            Map.entry("pragma_table_xinfo", 3026000),
            Map.entry("pragma_function_list", 3030000),
            Map.entry("pragma_module_list", 3030000),
            Map.entry("iif", 3032000),
            Map.entry("substring", 3034000),
            Map.entry("pragma_table_list", 3037000),
            Map.entry("format", 3038000),
            Map.entry("unixepoch", 3038000),
            Map.entry("unhex", 3041000),
            Map.entry("octet_length", 3043000),
            Map.entry("timediff", 3043000),
            Map.entry("concat", 3044000),
            Map.entry("concat_ws", 3044000),
            Map.entry("string_agg", 3044000),
            Map.entry("if", 3048000),
            Map.entry("unistr", 3050000),
            Map.entry("unistr_quote", 3050000));

    /**
     * Version floors for whole function families, keyed by name prefix
     * ({@code ir.ts FUNCTION_PREFIX_MIN_VERSION}) — the LONGEST matching
     * prefix wins. Covers the JSON surface, too large to enumerate by hand.
     */
    public static final Map<String, Integer> FUNCTION_PREFIX_MIN_VERSION = Map.of(
            "json", 3038000,
            "jsonb", 3045000);

    /**
     * One version-gated SQL SYNTAX construct ({@code ir.ts SyntaxFeatureIr}):
     * the SQLITE_VERSION_NUMBER that introduced it and a description phrased
     * to drop into "SQL uses &lt;description&gt;, which requires SQLite ...".
     */
    public record SyntaxFeature(int minVersionNumber, String description) {
    }

    /**
     * SQL syntax introduced above the default floor
     * ({@code ir.ts SYNTAX_MIN_VERSION}), keyed by a stable feature id — the
     * sibling of {@link #FUNCTION_MIN_VERSION} for the half of the surface
     * that is grammar rather than a call. Detection is hand-written per
     * language (one token pattern per id); only the version and the wording
     * live here.
     */
    public static final Map<String, SyntaxFeature> SYNTAX_MIN_VERSION = Map.ofEntries(
            Map.entry("insert-alias", new SyntaxFeature(
                    3024000, "the INSERT table alias (INSERT INTO t AS alias)")),
            Map.entry("upsert", new SyntaxFeature(
                    3024000, "UPSERT (ON CONFLICT ... DO NOTHING/UPDATE)")),
            Map.entry("window-functions", new SyntaxFeature(
                    3025000, "the OVER window clause")),
            Map.entry("aggregate-filter", new SyntaxFeature(
                    3030000, "the FILTER clause on an aggregate")),
            Map.entry("nulls-first-last", new SyntaxFeature(
                    3030000, "NULLS FIRST / NULLS LAST in ORDER BY")),
            Map.entry("update-from", new SyntaxFeature(
                    3033000, "UPDATE ... FROM")),
            Map.entry("returning", new SyntaxFeature(
                    3035000, "the RETURNING clause")),
            Map.entry("materialized-cte", new SyntaxFeature(
                    3035000, "the MATERIALIZED / NOT MATERIALIZED CTE hint")),
            Map.entry("json-arrow-operators", new SyntaxFeature(
                    3038000, "the -> and ->> JSON operators")),
            Map.entry("right-full-join", new SyntaxFeature(
                    3039000, "RIGHT JOIN / FULL JOIN")),
            Map.entry("is-distinct-from", new SyntaxFeature(
                    3039000, "IS [NOT] DISTINCT FROM")));

    /**
     * Built-ins whose presence is decided by the device engine's compile
     * options rather than its version ({@code ir.ts NONPORTABLE_FUNCTIONS}),
     * so no version floor can make them safe.
     */
    public static final Set<String> NONPORTABLE_FUNCTIONS = Set.of(
            "acos", "acosh", "asin", "asinh", "atan", "atan2", "atanh", "ceil",
            "ceiling", "cos", "cosh", "degrees", "exp", "floor", "ln",
            "load_extension", "log", "log10", "log2", "mod", "pi", "pow",
            "power", "radians", "sin", "sinh", "soundex", "sqlite_offset",
            "sqrt", "tan", "tanh", "trunc");

    /**
     * Statement kinds a script may not use, matched on the statement's first
     * meaningful token ({@code ir.ts FORBIDDEN_LEADING_KEYWORDS}).
     */
    public static final Set<String> FORBIDDEN_LEADING_KEYWORDS = Set.of(
            "alter", "analyze", "attach", "begin", "commit", "create", "detach",
            "drop", "end", "explain", "pragma", "reindex", "release", "rollback",
            "savepoint", "vacuum");

    /**
     * Built-ins a script may not call at all
     * ({@code ir.ts FORBIDDEN_FUNCTIONS}), because calling one does what the
     * statement denylist exists to prevent. Matched wherever the identifier
     * appears — as a call or bare in table position.
     */
    public static final Set<String> FORBIDDEN_FUNCTIONS = Set.of(
            "pragma_optimize");

    /**
     * Tables SQLite itself owns ({@code ir.ts SYSTEM_TABLES}). A write
     * against one is a protocol-table-write, alongside the manifest-derived
     * runtime tables; unlike those, these names are fixed rather than
     * host-configurable. Reads stay legal.
     */
    public static final Set<String> SYSTEM_TABLES = Set.of(
            "sqlite_master", "sqlite_schema", "sqlite_sequence", "sqlite_stat1",
            "sqlite_stat2", "sqlite_stat3", "sqlite_stat4", "sqlite_temp_master",
            "sqlite_temp_schema");

    private Protocol() {
    }
}
