// <auto-generated />

using System;
using System.Collections.Generic;

namespace SqliteHost
{
    /// <summary>
    /// Protocol constants projected from codegen/core/src/ir.ts
    /// (docs/proposals/rule-parameters-as-data.md). Do not edit by hand —
    /// regenerate via the C# emitter; the cross-language golden pins this.
    /// </summary>
    internal static class ProtocolConstants
    {
        /// <summary>
        /// Reserved initial queue status (ir.ts PENDING_STATUS). The queue
        /// DDL defaults new rows to this literal and the runtime drain
        /// selects rows with this status; a doneValue equal to it would
        /// leave drained rows selectable, so it is rejected at registration.
        /// </summary>
        internal const string PendingStatus = "pending";

        /// <summary>
        /// Control-table action verbs (ir.ts CONTROL_ACTION_HALT /
        /// CONTROL_ACTION_FAIL). The runtime branches the control row's
        /// action on these; any other value is an invalid-control-action.
        /// </summary>
        internal const string ControlActionHalt = "halt";
        internal const string ControlActionFail = "fail";

        /// <summary>
        /// Feature flag a runtime advertises (ir.ts FEATURE_INLINE_FUNCTIONS)
        /// when its connection factory is scalar-function-capable and the
        /// host exposes at least one inline function.
        /// </summary>
        internal const string FeatureInlineFunctions = "inlineFunctions";

        /// <summary>
        /// Script envelope engine identifier (ir.ts ENGINE_V1). A script
        /// whose engine is anything else is rejected before any statement
        /// runs; the Java and TypeScript envelopes carry the same literal.
        /// </summary>
        internal const string EngineV1 = "sqlite-host-v1";

        /// <summary>
        /// Minimum SQLite a host requires when its definition does not say
        /// otherwise (ir.ts DEFAULT_MIN_SQLITE_VERSION_NUMBER): 3.19.3 in
        /// SQLITE_VERSION_NUMBER form.
        /// </summary>
        internal const int DefaultMinSqliteVersionNumber = 3019003;

        /// <summary>
        /// Protocol v1 features every definition advertises (ir.ts
        /// FEATURES_V1), in manifest order. FeatureInlineFunctions is not
        /// one of them: it is factory-conditional and added by the runtime.
        /// </summary>
        internal static readonly IReadOnlyList<string> FeaturesV1 =
            new List<string>
            {
                "typedNamedBindings",
                "splitResultTables",
                "scriptInputs",
                "scriptVars",
                "scriptControl"
            };

#if !SQLITEHOST_SLIM
        /// <summary>
        /// Method-name shape (ir.ts METHOD_NAME_PATTERN). The registration
        /// validator ships a hand-rolled char-scan instead of
        /// System.Text.RegularExpressions (netstandard2.0/Unity size); the
        /// test suite pins that scan to this canonical pattern.
        /// </summary>
        internal const string MethodNamePattern = "^[A-Za-z][A-Za-z0-9_]*$";

        /// <summary>
        /// SQLite built-in function names an inline function name must not
        /// collide with (ir.ts SQLITE_BUILTIN_FUNCTIONS). SQLite resolves
        /// function names case-insensitively, so membership ignores case.
        /// </summary>
        internal static readonly HashSet<string> SqliteBuiltinFunctions =
            new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "abs",
                "coalesce",
                "count",
                "sum",
                "min",
                "max",
                "length",
                "lower",
                "upper",
                "printf",
                "random",
                "replace",
                "round",
                "substr",
                "trim",
                "date",
                "time",
                "datetime",
                "ifnull",
                "nullif",
                "instr",
                "hex",
                "quote",
                "total",
                "group_concat",
                "typeof",
                "unicode",
                "char",
                "likelihood",
                "likely",
                "unlikely",
                "last_insert_rowid",
                "changes",
                "sqlite_version",
                "glob",
                "like",
                "zeroblob"
            };
#endif
    }
}
