/**
 * Deterministic text-layout helpers for the TypeScript emitters: greedy
 * comment wrapping and a fit-or-expand object/array literal printer.
 * All widths are fixed constants so the same IR always renders the
 * same bytes (the vendored generated sources are byte-golden).
 */

/** Max width of a rendered code line before a literal is expanded. */
const CODE_WIDTH = 80;

/** Max width of a wrapped comment line, including its `// `/` * ` prefix. */
const COMMENT_WIDTH = 72;

/** Greedy word-wrap of `text`, each line starting with `prefix`. */
function wrapWords(text: string, prefix: string): string[] {
  const words = text.split(/\s+/).filter((word) => word.length > 0);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    if (
      current !== "" &&
      prefix.length + current.length + 1 + word.length > COMMENT_WIDTH
    ) {
      lines.push(prefix + current);
      current = word;
    } else {
      current = current === "" ? word : `${current} ${word}`;
    }
  }
  if (current !== "") {
    lines.push(prefix + current);
  }
  return lines;
}

/** `// <auto-generated />` marker followed by wrapped `// ` lines. */
export function generatedHeader(text: string): string {
  return ["// <auto-generated />", ...wrapWords(text, "// ")].join("\n");
}

/** JSDoc comment: single line when it fits CODE_WIDTH, else a block. */
export function docComment(text: string, indent = ""): string {
  const oneLine = `${indent}/** ${text} */`;
  if (oneLine.length <= CODE_WIDTH) {
    return oneLine;
  }
  const body = wrapWords(text, `${indent} * `).join("\n");
  return `${indent}/**\n${body}\n${indent} */`;
}

/** JSON-like value rendered as a TypeScript object/array literal. */
export type Literal =
  | string
  | number
  | boolean
  | Literal[]
  | { [key: string]: Literal };

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function keyText(key: string): string {
  return IDENTIFIER.test(key) ? key : JSON.stringify(key);
}

function inlineLiteral(value: Literal): string {
  if (Array.isArray(value)) {
    return value.length === 0
      ? "[]"
      : `[${value.map(inlineLiteral).join(", ")}]`;
  }
  if (typeof value === "object" && value !== null) {
    const entries = Object.entries(value);
    return entries.length === 0
      ? "{}"
      : `{ ${entries
          .map(([key, item]) => `${keyText(key)}: ${inlineLiteral(item)}`)
          .join(", ")} }`;
  }
  return typeof value === "string" ? JSON.stringify(value) : String(value);
}

/**
 * Render a literal, keeping containers on one line whenever
 * `indent + prefix + literal + suffix` fits in CODE_WIDTH and otherwise
 * expanding them one entry per line (recursively, trailing commas).
 * `prefixWidth`/`suffixWidth` are the widths of whatever the caller
 * puts before/after the literal on its first line (e.g. `key: ` / `,`).
 */
export function renderLiteral(
  value: Literal,
  indent: string,
  prefixWidth: number,
  suffixWidth: number,
): string {
  const inline = inlineLiteral(value);
  if (
    typeof value !== "object" ||
    value === null ||
    indent.length + prefixWidth + inline.length + suffixWidth <= CODE_WIDTH
  ) {
    return inline;
  }
  const inner = `${indent}  `;
  if (Array.isArray(value)) {
    const lines = value.map(
      (item) => `${inner}${renderLiteral(item, inner, 0, 1)},`,
    );
    return `[\n${lines.join("\n")}\n${indent}]`;
  }
  const lines = Object.entries(value).map(([key, item]) => {
    const prefix = `${keyText(key)}: `;
    return `${inner}${prefix}${renderLiteral(item, inner, prefix.length, 1)},`;
  });
  return `{\n${lines.join("\n")}\n${indent}}`;
}
