/**
 * C# code emission from the SqliteHost IR. Maps a host library IR to the
 * generated C# sources: DTO classes, handler interface, fluent method
 * specs, host definition, schema SQL constant, and the protocol script
 * envelope DTOs (vendored into SqliteHost.Abstractions). Three size
 * profiles are supported (docs/csharp-api.md "Profile deltas"): classic
 * (typed fluent specs, the default), compact (pre-erased static accessor
 * methods, no lambdas), and ultra (no DTOs; erased call/result handlers).
 * Output is byte-identical to the committed sources under csharp/ — the
 * repo files are the goldens (docs/csharp-api.md "Generated code shape").
 */

import {
  generateSchemaScript,
  type HostLibraryIr,
  type HostMethodIr,
  type ListFieldIr,
  type ObjectShapeIr,
  type ScalarFieldIr,
} from "@sqlite-host/codegen-core";

export interface EmittedFile {
  /**
   * Output path relative to the emit root. Per-app files sit at the
   * root; the protocol envelope (app-independent, vendored into the
   * abstractions package) is distinguished by the envelope/ prefix.
   */
  path: string;
  contents: string;
}

const HEADER = "// <auto-generated />";

export const DTOS_FILE = "HostMethodDtos.g.cs";
export const HANDLERS_FILE = "IGeneratedHostHandlers.g.cs";
export const SPECS_FILE = "GeneratedHostMethodSpecs.g.cs";
export const DEFINITION_FILE = "GeneratedHostDefinition.g.cs";
export const SCHEMA_FILE = "GeneratedSchemaSql.g.cs";
export const ENVELOPE_FILE = "envelope/ScriptEnvelope.g.cs";

/** Generated namespace: the library namespace with a .Generated suffix. */
export function generatedNamespace(ir: HostLibraryIr): string {
  return `${ir.library.namespace}.Generated`;
}

function pascalCase(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

/** Render a C# string literal (quotes included). */
function csharpString(value: string): string {
  let out = "";
  for (const ch of value) {
    switch (ch) {
      case "\\":
        out += "\\\\";
        break;
      case '"':
        out += '\\"';
        break;
      case "\n":
        out += "\\n";
        break;
      case "\r":
        out += "\\r";
        break;
      case "\t":
        out += "\\t";
        break;
      default:
        out += ch;
    }
  }
  return `"${out}"`;
}

/** C# property type for a scalar field (optional value scalars are nullable). */
function propertyType(field: ScalarFieldIr): string {
  switch (field.scalarType) {
    case "int32":
      return field.optional ? "int?" : "int";
    case "int64":
      return field.optional ? "long?" : "long";
    case "boolean":
      return field.optional ? "bool?" : "bool";
    case "string":
      return "string";
    case "bytes":
      return "byte[]";
    case "float32":
      return field.optional ? "float?" : "float";
    case "float64":
      return field.optional ? "double?" : "double";
  }
}

/** Fluent field-builder method name (Text/Long/Int/Bool/Blob, Optional*). */
function builderMethod(field: ScalarFieldIr): string {
  let base: string;
  switch (field.scalarType) {
    case "int32":
      base = "Int";
      break;
    case "int64":
      base = "Long";
      break;
    case "boolean":
      base = "Bool";
      break;
    case "string":
      base = "Text";
      break;
    case "bytes":
      base = "Blob";
      break;
    case "float32":
      base = "Float";
      break;
    case "float64":
      base = "Double";
      break;
  }
  return field.optional ? `Optional${base}` : base;
}

// ---------------------------------------------------------------------------
// HostMethodDtos.g.cs
// ---------------------------------------------------------------------------

export function emitHostMethodDtos(
  ir: HostLibraryIr,
  ns: string = generatedNamespace(ir),
): string {
  const classes: string[] = [];
  const seen = new Set<string>();

  const addClass = (
    modelName: string,
    fields: ScalarFieldIr[],
    listFields: ListFieldIr[],
  ): void => {
    if (seen.has(modelName)) {
      return;
    }
    seen.add(modelName);
    const lines = [`    public class ${modelName}`, "    {"];
    for (const field of fields) {
      lines.push(
        `        public ${propertyType(field)} ${pascalCase(field.propertyName)} { get; set; }`,
      );
    }
    for (const listField of listFields) {
      const item = listField.itemModelName;
      lines.push(
        `        public List<${item}> ${pascalCase(listField.propertyName)} { get; set; } = new List<${item}>();`,
      );
    }
    lines.push("    }");
    classes.push(lines.join("\n"));
  };

  const addShape = (shape: ObjectShapeIr): void => {
    addClass(shape.modelName, shape.fields, shape.listFields);
    for (const listField of shape.listFields) {
      addClass(listField.itemModelName, listField.itemFields, []);
    }
  };

  for (const method of ir.methods) {
    addShape(method.input);
    addShape(method.result);
  }

  const usesLists = ir.methods.some(
    (m) => m.input.listFields.length > 0 || m.result.listFields.length > 0,
  );
  const head = usesLists
    ? [HEADER, "", "using System.Collections.Generic;", ""]
    : [HEADER, ""];
  return [
    ...head,
    `namespace ${ns}`,
    "{",
    classes.join("\n\n"),
    "}",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// IGeneratedHostHandlers.g.cs
// ---------------------------------------------------------------------------

export function emitHandlerInterface(
  ir: HostLibraryIr,
  ns: string = generatedNamespace(ir),
): string {
  const lines = [
    HEADER,
    "",
    `namespace ${ns}`,
    "{",
    "    public interface IGeneratedHostHandlers",
    "    {",
  ];
  for (const method of ir.methods) {
    lines.push(
      `        ${method.result.modelName} ${method.handlerName}(${method.input.modelName} input);`,
    );
  }
  lines.push("    }", "}", "");
  return lines.join("\n");
}

/**
 * Ultra profile: no DTOs exist, so handlers take the erased
 * SqliteHostUltraCall and return the erased SqliteHostUltraResult.
 */
export function emitUltraHandlerInterface(
  ir: HostLibraryIr,
  ns: string = generatedNamespace(ir),
): string {
  const lines = [
    HEADER,
    "",
    "using SqliteHost;",
    "",
    `namespace ${ns}`,
    "{",
    "    public interface IGeneratedHostHandlers",
    "    {",
  ];
  for (const method of ir.methods) {
    lines.push(
      `        SqliteHostUltraResult ${method.handlerName}(SqliteHostUltraCall call);`,
    );
  }
  lines.push("    }", "}", "");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// GeneratedHostMethodSpecs.g.cs
// ---------------------------------------------------------------------------

/** One fluent field call, possibly spanning extra lines for a list. */
interface FieldCall {
  first: string;
  itemLines: string[];
}

function inputScalarCall(field: ScalarFieldIr): string {
  return `.${builderMethod(field)}(${csharpString(field.sqlName)}, (x, v) => x.${pascalCase(field.propertyName)} = v)`;
}

function resultScalarCall(field: ScalarFieldIr): string {
  return `.${builderMethod(field)}(${csharpString(field.sqlName)}, x => x.${pascalCase(field.propertyName)})`;
}

function shapeCalls(shape: ObjectShapeIr, isInput: boolean): FieldCall[] {
  const calls: FieldCall[] = [];
  const scalarCall = isInput ? inputScalarCall : resultScalarCall;
  for (const field of shape.fields) {
    calls.push({ first: scalarCall(field), itemLines: [] });
  }
  for (const listField of shape.listFields) {
    const pascal = pascalCase(listField.propertyName);
    const accessor = isInput ? `(x, v) => x.${pascal} = v` : `x => x.${pascal}`;
    const itemLines = listField.itemFields.map((field) => scalarCall(field));
    // Close the item lambda on its last field call.
    itemLines[itemLines.length - 1] += ")";
    calls.push({
      first: `.List<${listField.itemModelName}>(${csharpString(listField.sqlName)}, ${accessor}, item => item`,
      itemLines,
    });
  }
  return calls;
}

/**
 * Render a `.Inputs(i => i ...)` / `.Results(r => r ...)` block. Empty
 * shapes emit nothing (the fluent API takes an Action; a call-less
 * lambda would not compile).
 */
function fieldBlock(
  group: "Inputs" | "Results",
  shape: ObjectShapeIr,
  isInput: boolean,
): string[] {
  const calls = shapeCalls(shape, isInput);
  if (calls.length === 0) {
    return [];
  }
  const param = isInput ? "i" : "r";
  const lines = [`                .${group}(${param} => ${param}`];
  for (const call of calls) {
    lines.push(`                    ${call.first}`);
    for (const itemLine of call.itemLines) {
      lines.push(`                        ${itemLine}`);
    }
  }
  // Close the group lambda on its last line.
  lines[lines.length - 1] += ")";
  return lines;
}

function specMethod(method: HostMethodIr): string {
  // Inline scalar-function exposure sits between .Results and .Handler
  // (docs/csharp-api.md); non-inline methods emit nothing.
  const inline =
    method.inline === null
      ? []
      : [`                .Inline(${csharpString(method.inline.functionName)})`];
  const lines = [
    `        private static IHostMethodSpec<IGeneratedHostHandlers> Build${method.operationName}Spec()`,
    "        {",
    "            return HostMethod",
    `                .For<IGeneratedHostHandlers, ${method.input.modelName}, ${method.result.modelName}>(${csharpString(method.methodName)})`,
    `                .ApiLevel(${method.apiLevel})`,
    ...fieldBlock("Inputs", method.input, true),
    ...fieldBlock("Results", method.result, false),
    ...inline,
    `                .Handler((handlers, input) => handlers.${method.handlerName}(input))`,
    "                .Build();",
    "        }",
  ];
  return lines.join("\n");
}

/** The BuildAll() member — identical across the three profiles. */
function buildAllMember(ir: HostLibraryIr): string {
  return [
    "        public static IReadOnlyList<IHostMethodSpec<IGeneratedHostHandlers>> BuildAll()",
    "        {",
    "            return new IHostMethodSpec<IGeneratedHostHandlers>[]",
    "            {",
    ...ir.methods.map((m) => `                Build${m.operationName}Spec(),`),
    "            };",
    "        }",
  ].join("\n");
}

/** Shared GeneratedHostMethodSpecs.g.cs scaffolding around the members. */
function specsFile(ns: string, members: string[]): string {
  return [
    HEADER,
    "",
    "using System.Collections.Generic;",
    "using SqliteHost;",
    "",
    `namespace ${ns}`,
    "{",
    "    public static class GeneratedHostMethodSpecs",
    "    {",
    members.join("\n\n"),
    "    }",
    "}",
    "",
  ].join("\n");
}

export function emitMethodSpecs(
  ir: HostLibraryIr,
  ns: string = generatedNamespace(ir),
): string {
  return specsFile(ns, [buildAllMember(ir), ...ir.methods.map(specMethod)]);
}

// ---------------------------------------------------------------------------
// GeneratedHostMethodSpecs.g.cs (compact profile)
// ---------------------------------------------------------------------------

/**
 * Compact accessor naming contract (docs/csharp-api.md "Profile deltas"):
 * Create{Op}Input / Set{Op}{Field} / Read{Op}{Field} for scalars,
 * Create{Op}{List}Item + Configure{Op}{List}Item + Set{ItemDto}{Field} +
 * Assign{Op}{List} for input lists, Read{Op}{List} +
 * Configure{Op}{List}Item + Read{ItemDto}{Field} for result lists, and
 * Invoke{Op} for the handler thunk. Item-DTO accessors are keyed by the
 * item class, so they are emitted once per file even when lists share a
 * DTO (mirrors the DTO dedup above).
 */

/** `private static void Set...(object input, T value)` property setter. */
function compactSetterMember(
  name: string,
  modelName: string,
  param: "input" | "item",
  field: ScalarFieldIr,
): string {
  return [
    `        private static void ${name}(object ${param}, ${propertyType(field)} value)`,
    "        {",
    `            ((${modelName})${param}).${pascalCase(field.propertyName)} = value;`,
    "        }",
  ].join("\n");
}

/** `private static T Read...(object result)` property reader. */
function compactReaderMember(
  name: string,
  modelName: string,
  param: "result" | "item",
  field: ScalarFieldIr,
): string {
  return [
    `        private static ${propertyType(field)} ${name}(object ${param})`,
    "        {",
    `            return ((${modelName})${param}).${pascalCase(field.propertyName)};`,
    "        }",
  ].join("\n");
}

/** `private static void Configure...Item(...)` with one field call per line. */
function configureItemMember(
  name: string,
  builderType: string,
  calls: string[],
): string {
  const chained = calls.map((call) => `                ${call}`);
  // Close the statement on its last field call.
  chained[chained.length - 1] += ";";
  return [
    `        private static void ${name}(${builderType} item)`,
    "        {",
    "            item",
    ...chained,
    "        }",
  ].join("\n");
}

/**
 * The Build{Op}Spec() member followed by its accessor statics, in spec
 * chain order: create-input, input scalars, input lists (create item,
 * configure, item setters, assign), result scalars, result lists (read,
 * configure, item readers), invoke.
 */
function compactSpecMembers(
  method: HostMethodIr,
  seenItemAccessors: Set<string>,
): string[] {
  const op = method.operationName;
  const members: string[] = [];

  // Inline scalar-function exposure sits between the last Result* call
  // and .Handler, exactly as in the classic profile.
  const inline =
    method.inline === null
      ? []
      : [`                .Inline(${csharpString(method.inline.functionName)})`];
  members.push(
    [
      `        private static IHostMethodSpec<IGeneratedHostHandlers> Build${op}Spec()`,
      "        {",
      "            return CompactHostMethod",
      `                .For<IGeneratedHostHandlers>(${csharpString(method.methodName)})`,
      `                .ApiLevel(${method.apiLevel})`,
      `                .CreateInput(Create${op}Input)`,
      ...method.input.fields.map(
        (field) =>
          `                .Input${builderMethod(field)}(${csharpString(field.sqlName)}, Set${op}${pascalCase(field.propertyName)})`,
      ),
      ...method.input.listFields.map((listField) => {
        const list = pascalCase(listField.propertyName);
        return `                .InputList(${csharpString(listField.sqlName)}, Create${op}${list}Item, Assign${op}${list}, Configure${op}${list}Item)`;
      }),
      ...method.result.fields.map(
        (field) =>
          `                .Result${builderMethod(field)}(${csharpString(field.sqlName)}, Read${op}${pascalCase(field.propertyName)})`,
      ),
      ...method.result.listFields.map((listField) => {
        const list = pascalCase(listField.propertyName);
        return `                .ResultList(${csharpString(listField.sqlName)}, Read${op}${list}, Configure${op}${list}Item)`;
      }),
      ...inline,
      `                .Handler(Invoke${op})`,
      "                .Build();",
      "        }",
    ].join("\n"),
  );

  members.push(
    [
      `        private static object Create${op}Input()`,
      "        {",
      `            return new ${method.input.modelName}();`,
      "        }",
    ].join("\n"),
  );

  for (const field of method.input.fields) {
    members.push(
      compactSetterMember(
        `Set${op}${pascalCase(field.propertyName)}`,
        method.input.modelName,
        "input",
        field,
      ),
    );
  }

  for (const listField of method.input.listFields) {
    const list = pascalCase(listField.propertyName);
    const item = listField.itemModelName;
    members.push(
      [
        `        private static object Create${op}${list}Item()`,
        "        {",
        `            return new ${item}();`,
        "        }",
      ].join("\n"),
    );
    members.push(
      configureItemMember(
        `Configure${op}${list}Item`,
        "ICompactListItemFieldsBuilder",
        listField.itemFields.map(
          (field) =>
            `.${builderMethod(field)}(${csharpString(field.sqlName)}, Set${item}${pascalCase(field.propertyName)})`,
        ),
      ),
    );
    if (!seenItemAccessors.has(`Set${item}`)) {
      seenItemAccessors.add(`Set${item}`);
      for (const field of listField.itemFields) {
        members.push(
          compactSetterMember(
            `Set${item}${pascalCase(field.propertyName)}`,
            item,
            "item",
            field,
          ),
        );
      }
    }
    members.push(
      [
        `        private static void Assign${op}${list}(object input, IReadOnlyList<object> items)`,
        "        {",
        `            var list = new List<${item}>(items.Count);`,
        "            for (int i = 0; i < items.Count; i++)",
        "            {",
        `                list.Add((${item})items[i]);`,
        "            }",
        `            ((${method.input.modelName})input).${list} = list;`,
        "        }",
      ].join("\n"),
    );
  }

  for (const field of method.result.fields) {
    members.push(
      compactReaderMember(
        `Read${op}${pascalCase(field.propertyName)}`,
        method.result.modelName,
        "result",
        field,
      ),
    );
  }

  for (const listField of method.result.listFields) {
    const list = pascalCase(listField.propertyName);
    const item = listField.itemModelName;
    members.push(
      [
        `        private static IReadOnlyList<object> Read${op}${list}(object result)`,
        "        {",
        `            List<${item}> items = ((${method.result.modelName})result).${list};`,
        "            if (items == null)",
        "            {",
        "                return null;",
        "            }",
        "            var list = new List<object>(items.Count);",
        "            for (int i = 0; i < items.Count; i++)",
        "            {",
        "                list.Add(items[i]);",
        "            }",
        "            return list;",
        "        }",
      ].join("\n"),
    );
    members.push(
      configureItemMember(
        `Configure${op}${list}Item`,
        "ICompactListItemResultFieldsBuilder",
        listField.itemFields.map(
          (field) =>
            `.${builderMethod(field)}(${csharpString(field.sqlName)}, Read${item}${pascalCase(field.propertyName)})`,
        ),
      ),
    );
    if (!seenItemAccessors.has(`Read${item}`)) {
      seenItemAccessors.add(`Read${item}`);
      for (const field of listField.itemFields) {
        members.push(
          compactReaderMember(
            `Read${item}${pascalCase(field.propertyName)}`,
            item,
            "item",
            field,
          ),
        );
      }
    }
  }

  members.push(
    [
      `        private static object Invoke${op}(object handlers, object input)`,
      "        {",
      `            return ((IGeneratedHostHandlers)handlers).${method.handlerName}((${method.input.modelName})input);`,
      "        }",
    ].join("\n"),
  );

  return members;
}

export function emitCompactMethodSpecs(
  ir: HostLibraryIr,
  ns: string = generatedNamespace(ir),
): string {
  const seenItemAccessors = new Set<string>();
  return specsFile(ns, [
    buildAllMember(ir),
    ...ir.methods.flatMap((m) => compactSpecMembers(m, seenItemAccessors)),
  ]);
}

// ---------------------------------------------------------------------------
// GeneratedHostMethodSpecs.g.cs (ultra profile)
// ---------------------------------------------------------------------------

/**
 * The Build{Op}Spec() member followed by its statics: declaration-only
 * field calls need no accessors, so only Configure{Op}{List}Item (input
 * lists then result lists) and the Invoke{Op} handler thunk remain.
 */
function ultraSpecMembers(method: HostMethodIr): string[] {
  const op = method.operationName;
  const members: string[] = [];

  const inline =
    method.inline === null
      ? []
      : [`                .Inline(${csharpString(method.inline.functionName)})`];
  members.push(
    [
      `        private static IHostMethodSpec<IGeneratedHostHandlers> Build${op}Spec()`,
      "        {",
      "            return UltraHostMethod",
      `                .For<IGeneratedHostHandlers>(${csharpString(method.methodName)})`,
      `                .ApiLevel(${method.apiLevel})`,
      ...method.input.fields.map(
        (field) =>
          `                .Input${builderMethod(field)}(${csharpString(field.sqlName)})`,
      ),
      ...method.input.listFields.map(
        (listField) =>
          `                .InputList(${csharpString(listField.sqlName)}, Configure${op}${pascalCase(listField.propertyName)}Item)`,
      ),
      ...method.result.fields.map(
        (field) =>
          `                .Result${builderMethod(field)}(${csharpString(field.sqlName)})`,
      ),
      ...method.result.listFields.map(
        (listField) =>
          `                .ResultList(${csharpString(listField.sqlName)}, Configure${op}${pascalCase(listField.propertyName)}Item)`,
      ),
      ...inline,
      `                .Handler(Invoke${op})`,
      "                .Build();",
      "        }",
    ].join("\n"),
  );

  for (const listField of [
    ...method.input.listFields,
    ...method.result.listFields,
  ]) {
    members.push(
      configureItemMember(
        `Configure${op}${pascalCase(listField.propertyName)}Item`,
        "IUltraListItemFieldsBuilder",
        listField.itemFields.map(
          (field) => `.${builderMethod(field)}(${csharpString(field.sqlName)})`,
        ),
      ),
    );
  }

  members.push(
    [
      `        private static SqliteHostUltraResult Invoke${op}(object handlers, SqliteHostUltraCall call)`,
      "        {",
      `            return ((IGeneratedHostHandlers)handlers).${method.handlerName}(call);`,
      "        }",
    ].join("\n"),
  );

  return members;
}

export function emitUltraMethodSpecs(
  ir: HostLibraryIr,
  ns: string = generatedNamespace(ir),
): string {
  return specsFile(ns, [
    buildAllMember(ir),
    ...ir.methods.flatMap(ultraSpecMembers),
  ]);
}

// ---------------------------------------------------------------------------
// GeneratedHostDefinition.g.cs
// ---------------------------------------------------------------------------

export function emitHostDefinition(
  ir: HostLibraryIr,
  ns: string = generatedNamespace(ir),
): string {
  const naming = ir.naming;
  const columns = ir.columns;
  return [
    HEADER,
    "",
    "using SqliteHost;",
    "",
    `namespace ${ns}`,
    "{",
    "    public static class GeneratedHostDefinition",
    "    {",
    "        public static SqliteHostDefinition<IGeneratedHostHandlers> Build()",
    "        {",
    "            return SqliteHostDefinition",
    "                .ForHandlers<IGeneratedHostHandlers>()",
    `                .ApiLevel(${ir.library.apiLevel})`,
    `                .MinSqliteVersion(${ir.library.minSqliteVersionNumber})`,
    "                .Naming(n => n",
    `                    .CallTablePrefix(${csharpString(naming.callTablePrefix)})`,
    `                    .ResultTablePrefix(${csharpString(naming.resultTablePrefix)})`,
    `                    .InputColumnPrefix(${csharpString(naming.inputColumnPrefix)})`,
    `                    .ResultColumnPrefix(${csharpString(naming.resultColumnPrefix)})`,
    `                    .InputListTableInfix(${csharpString(naming.inputListTableInfix)})`,
    `                    .ResultListTableInfix(${csharpString(naming.resultListTableInfix)})`,
    `                    .QueueTable(${csharpString(ir.queueTable.name)})`,
    `                    .InputsTable(${csharpString(ir.inputsTable.name)})`,
    `                    .VarsTable(${csharpString(ir.varsTable.name)})`,
    `                    .ControlTable(${csharpString(ir.controlTable.name)})`,
    `                    .FunctionPrefix(${csharpString(naming.functionPrefix)}))`,
    // All fourteen column values are always emitted explicitly, in
    // SqliteHostColumns property order (docs/csharp-api.md).
    "                .Columns(c => c",
    `                    .CallId(${csharpString(columns.callId)})`,
    `                    .ItemIndex(${csharpString(columns.itemIndex)})`,
    `                    .Status(${csharpString(columns.status)})`,
    `                    .DoneValue(${csharpString(columns.doneValue)})`,
    `                    .QueueId(${csharpString(columns.queueId)})`,
    `                    .Method(${csharpString(columns.method)})`,
    `                    .Name(${csharpString(columns.name)})`,
    `                    .ValueType(${csharpString(columns.valueType)})`,
    `                    .IntValue(${csharpString(columns.intValue)})`,
    `                    .RealValue(${csharpString(columns.realValue)})`,
    `                    .TextValue(${csharpString(columns.textValue)})`,
    `                    .BlobValue(${csharpString(columns.blobValue)})`,
    `                    .Action(${csharpString(columns.action)})`,
    `                    .Message(${csharpString(columns.message)}))`,
    "                .Methods(GeneratedHostMethodSpecs.BuildAll());",
    "        }",
    "    }",
    "}",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// GeneratedSchemaSql.g.cs
// ---------------------------------------------------------------------------

export function emitSchemaSql(
  ir: HostLibraryIr,
  ns: string = generatedNamespace(ir),
): string {
  const script = generateSchemaScript(ir);
  const scriptLines = script.split("\n");
  // generateSchemaScript output ends with "\n"; drop the empty tail.
  scriptLines.pop();
  const segments = scriptLines.map((line) => csharpString(`${line}\n`));
  const literal = segments.map((segment, i) =>
    i === 0 ? `            ${segment}` : `            + ${segment}`,
  );
  literal[literal.length - 1] += ";";
  return [
    HEADER,
    "",
    `namespace ${ns}`,
    "{",
    "    public static class GeneratedSchemaSql",
    "    {",
    "        public const string SchemaScript =",
    ...literal,
    "    }",
    "}",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// ScriptEnvelope.g.cs (protocol v1, app-independent, vendored)
// ---------------------------------------------------------------------------

export function emitScriptEnvelope(): string {
  return [
    HEADER,
    "",
    "using System.Collections.Generic;",
    "",
    "namespace SqliteHost",
    "{",
    "    public class SqliteHostScript",
    "    {",
    "        public string Engine { get; set; }",
    "        public string ScriptId { get; set; }",
    "        public int RequiredApiLevel { get; set; }",
    "        public List<string> RequiredFeatures { get; set; }",
    "        public List<string> RequiredMethods { get; set; }",
    "        public List<SqliteHostRuntimeInput> Inputs { get; set; }",
    "        public List<SqliteHostStep> Steps { get; set; }",
    "    }",
    "",
    "    public class SqliteHostRuntimeInput",
    "    {",
    "        public string Name { get; set; }",
    "        public SqliteHostBindingValue Value { get; set; }",
    "    }",
    "",
    "    public class SqliteHostStep",
    "    {",
    "        public string Id { get; set; }",
    "        public List<SqliteHostStatement> Statements { get; set; }",
    "    }",
    "",
    "    public class SqliteHostStatement",
    "    {",
    "        public string Sql { get; set; }",
    "        public Dictionary<string, SqliteHostBindingValue> Bindings { get; set; }",
    "    }",
    "}",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/** Code-size profile (docs/csharp-api.md "Profile deltas"). */
export type CSharpProfile = "classic" | "compact" | "ultra";

export interface EmitCSharpOptions {
  /** Size profile to emit. Default "classic" — the original output. */
  profile?: CSharpProfile;
  /**
   * Replaces the generated namespace (library namespace + ".Generated")
   * in every emitted per-app file. The protocol envelope always stays
   * in the fixed SqliteHost namespace.
   */
  namespaceOverride?: string;
}

/** Emit all generated C# sources for a host library IR. */
export function emitCSharp(
  ir: HostLibraryIr,
  options: EmitCSharpOptions = {},
): EmittedFile[] {
  const profile = options.profile ?? "classic";
  const ns = options.namespaceOverride ?? generatedNamespace(ir);
  const files: EmittedFile[] = [];
  // Ultra has no DTOs at all; classic and compact share the same file.
  if (profile !== "ultra") {
    files.push({ path: DTOS_FILE, contents: emitHostMethodDtos(ir, ns) });
  }
  files.push(
    {
      path: HANDLERS_FILE,
      contents:
        profile === "ultra"
          ? emitUltraHandlerInterface(ir, ns)
          : emitHandlerInterface(ir, ns),
    },
    {
      path: SPECS_FILE,
      contents:
        profile === "classic"
          ? emitMethodSpecs(ir, ns)
          : profile === "compact"
            ? emitCompactMethodSpecs(ir, ns)
            : emitUltraMethodSpecs(ir, ns),
    },
    { path: DEFINITION_FILE, contents: emitHostDefinition(ir, ns) },
    { path: SCHEMA_FILE, contents: emitSchemaSql(ir, ns) },
    { path: ENVELOPE_FILE, contents: emitScriptEnvelope() },
  );
  return files;
}
