/**
 * C# code emission from the SqliteHost IR. Maps a host library IR to the
 * generated C# sources: DTO classes, handler interface, fluent method
 * specs, host definition, schema SQL constant, and the protocol script
 * envelope DTOs (vendored into SqliteHost.Abstractions). Output is
 * byte-identical to the committed sources under csharp/ — the repo files
 * are the goldens (docs/csharp-api.md "Generated code shape").
 */

import {
  generateSchemaScript,
  type HostLibraryIr,
  type HostMethodIr,
  type ListFieldIr,
  type ObjectShapeIr,
  type ScalarFieldIr,
} from "@sqlite-host/codegen-core";

export interface EmittedFile {
  /**
   * Output path relative to the emit root. Per-app files sit at the
   * root; the protocol envelope (app-independent, vendored into the
   * abstractions package) is distinguished by the envelope/ prefix.
   */
  path: string;
  contents: string;
}

const HEADER = "// <auto-generated />";

export const DTOS_FILE = "HostMethodDtos.g.cs";
export const HANDLERS_FILE = "IGeneratedHostHandlers.g.cs";
export const SPECS_FILE = "GeneratedHostMethodSpecs.g.cs";
export const DEFINITION_FILE = "GeneratedHostDefinition.g.cs";
export const SCHEMA_FILE = "GeneratedSchemaSql.g.cs";
export const ENVELOPE_FILE = "envelope/ScriptEnvelope.g.cs";

/** Generated namespace: the library namespace with a .Generated suffix. */
export function generatedNamespace(ir: HostLibraryIr): string {
  return `${ir.library.namespace}.Generated`;
}

function pascalCase(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

/** Render a C# string literal (quotes included). */
function csharpString(value: string): string {
  let out = "";
  for (const ch of value) {
    switch (ch) {
      case "\\":
        out += "\\\\";
        break;
      case '"':
        out += '\\"';
        break;
      case "\n":
        out += "\\n";
        break;
      case "\r":
        out += "\\r";
        break;
      case "\t":
        out += "\\t";
        break;
      default:
        out += ch;
    }
  }
  return `"${out}"`;
}

/** C# property type for a scalar field (optional value scalars are nullable). */
function propertyType(field: ScalarFieldIr): string {
  switch (field.scalarType) {
    case "int32":
      return field.optional ? "int?" : "int";
    case "int64":
      return field.optional ? "long?" : "long";
    case "boolean":
      return field.optional ? "bool?" : "bool";
    case "string":
      return "string";
    case "bytes":
      return "byte[]";
    case "float32":
      return field.optional ? "float?" : "float";
    case "float64":
      return field.optional ? "double?" : "double";
  }
}

/** Fluent field-builder method name (Text/Long/Int/Bool/Blob, Optional*). */
function builderMethod(field: ScalarFieldIr): string {
  let base: string;
  switch (field.scalarType) {
    case "int32":
      base = "Int";
      break;
    case "int64":
      base = "Long";
      break;
    case "boolean":
      base = "Bool";
      break;
    case "string":
      base = "Text";
      break;
    case "bytes":
      base = "Blob";
      break;
    case "float32":
      base = "Float";
      break;
    case "float64":
      base = "Double";
      break;
  }
  return field.optional ? `Optional${base}` : base;
}

// ---------------------------------------------------------------------------
// HostMethodDtos.g.cs
// ---------------------------------------------------------------------------

export function emitHostMethodDtos(ir: HostLibraryIr): string {
  const classes: string[] = [];
  const seen = new Set<string>();

  const addClass = (
    modelName: string,
    fields: ScalarFieldIr[],
    listFields: ListFieldIr[],
  ): void => {
    if (seen.has(modelName)) {
      return;
    }
    seen.add(modelName);
    const lines = [`    public class ${modelName}`, "    {"];
    for (const field of fields) {
      lines.push(
        `        public ${propertyType(field)} ${pascalCase(field.propertyName)} { get; set; }`,
      );
    }
    for (const listField of listFields) {
      const item = listField.itemModelName;
      lines.push(
        `        public List<${item}> ${pascalCase(listField.propertyName)} { get; set; } = new List<${item}>();`,
      );
    }
    lines.push("    }");
    classes.push(lines.join("\n"));
  };

  const addShape = (shape: ObjectShapeIr): void => {
    addClass(shape.modelName, shape.fields, shape.listFields);
    for (const listField of shape.listFields) {
      addClass(listField.itemModelName, listField.itemFields, []);
    }
  };

  for (const method of ir.methods) {
    addShape(method.input);
    addShape(method.result);
  }

  const usesLists = ir.methods.some(
    (m) => m.input.listFields.length > 0 || m.result.listFields.length > 0,
  );
  const head = usesLists
    ? [HEADER, "", "using System.Collections.Generic;", ""]
    : [HEADER, ""];
  return [
    ...head,
    `namespace ${generatedNamespace(ir)}`,
    "{",
    classes.join("\n\n"),
    "}",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// IGeneratedHostHandlers.g.cs
// ---------------------------------------------------------------------------

export function emitHandlerInterface(ir: HostLibraryIr): string {
  const lines = [
    HEADER,
    "",
    `namespace ${generatedNamespace(ir)}`,
    "{",
    "    public interface IGeneratedHostHandlers",
    "    {",
  ];
  for (const method of ir.methods) {
    lines.push(
      `        ${method.result.modelName} ${method.handlerName}(${method.input.modelName} input);`,
    );
  }
  lines.push("    }", "}", "");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// GeneratedHostMethodSpecs.g.cs
// ---------------------------------------------------------------------------

/** One fluent field call, possibly spanning extra lines for a list. */
interface FieldCall {
  first: string;
  itemLines: string[];
}

function inputScalarCall(field: ScalarFieldIr): string {
  return `.${builderMethod(field)}(${csharpString(field.sqlName)}, (x, v) => x.${pascalCase(field.propertyName)} = v)`;
}

function resultScalarCall(field: ScalarFieldIr): string {
  return `.${builderMethod(field)}(${csharpString(field.sqlName)}, x => x.${pascalCase(field.propertyName)})`;
}

function shapeCalls(shape: ObjectShapeIr, isInput: boolean): FieldCall[] {
  const calls: FieldCall[] = [];
  const scalarCall = isInput ? inputScalarCall : resultScalarCall;
  for (const field of shape.fields) {
    calls.push({ first: scalarCall(field), itemLines: [] });
  }
  for (const listField of shape.listFields) {
    const pascal = pascalCase(listField.propertyName);
    const accessor = isInput ? `(x, v) => x.${pascal} = v` : `x => x.${pascal}`;
    const itemLines = listField.itemFields.map((field) => scalarCall(field));
    // Close the item lambda on its last field call.
    itemLines[itemLines.length - 1] += ")";
    calls.push({
      first: `.List<${listField.itemModelName}>(${csharpString(listField.sqlName)}, ${accessor}, item => item`,
      itemLines,
    });
  }
  return calls;
}

/**
 * Render a `.Inputs(i => i ...)` / `.Results(r => r ...)` block. Empty
 * shapes emit nothing (the fluent API takes an Action; a call-less
 * lambda would not compile).
 */
function fieldBlock(
  group: "Inputs" | "Results",
  shape: ObjectShapeIr,
  isInput: boolean,
): string[] {
  const calls = shapeCalls(shape, isInput);
  if (calls.length === 0) {
    return [];
  }
  const param = isInput ? "i" : "r";
  const lines = [`                .${group}(${param} => ${param}`];
  for (const call of calls) {
    lines.push(`                    ${call.first}`);
    for (const itemLine of call.itemLines) {
      lines.push(`                        ${itemLine}`);
    }
  }
  // Close the group lambda on its last line.
  lines[lines.length - 1] += ")";
  return lines;
}

function specMethod(method: HostMethodIr): string {
  const lines = [
    `        private static IHostMethodSpec<IGeneratedHostHandlers> Build${method.operationName}Spec()`,
    "        {",
    "            return HostMethod",
    `                .For<IGeneratedHostHandlers, ${method.input.modelName}, ${method.result.modelName}>(${csharpString(method.methodName)})`,
    `                .ApiLevel(${method.apiLevel})`,
    ...fieldBlock("Inputs", method.input, true),
    ...fieldBlock("Results", method.result, false),
    `                .Handler((handlers, input) => handlers.${method.handlerName}(input))`,
    "                .Build();",
    "        }",
  ];
  return lines.join("\n");
}

export function emitMethodSpecs(ir: HostLibraryIr): string {
  const buildAll = [
    "        public static IReadOnlyList<IHostMethodSpec<IGeneratedHostHandlers>> BuildAll()",
    "        {",
    "            return new IHostMethodSpec<IGeneratedHostHandlers>[]",
    "            {",
    ...ir.methods.map((m) => `                Build${m.operationName}Spec(),`),
    "            };",
    "        }",
  ].join("\n");

  const members = [buildAll, ...ir.methods.map(specMethod)];
  return [
    HEADER,
    "",
    "using System.Collections.Generic;",
    "using SqliteHost;",
    "",
    `namespace ${generatedNamespace(ir)}`,
    "{",
    "    public static class GeneratedHostMethodSpecs",
    "    {",
    members.join("\n\n"),
    "    }",
    "}",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// GeneratedHostDefinition.g.cs
// ---------------------------------------------------------------------------

export function emitHostDefinition(ir: HostLibraryIr): string {
  const naming = ir.naming;
  const columns = ir.columns;
  return [
    HEADER,
    "",
    "using SqliteHost;",
    "",
    `namespace ${generatedNamespace(ir)}`,
    "{",
    "    public static class GeneratedHostDefinition",
    "    {",
    "        public static SqliteHostDefinition<IGeneratedHostHandlers> Build()",
    "        {",
    "            return SqliteHostDefinition",
    "                .ForHandlers<IGeneratedHostHandlers>()",
    `                .ApiLevel(${ir.library.apiLevel})`,
    `                .MinSqliteVersion(${ir.library.minSqliteVersionNumber})`,
    "                .Naming(n => n",
    `                    .CallTablePrefix(${csharpString(naming.callTablePrefix)})`,
    `                    .ResultTablePrefix(${csharpString(naming.resultTablePrefix)})`,
    `                    .InputColumnPrefix(${csharpString(naming.inputColumnPrefix)})`,
    `                    .ResultColumnPrefix(${csharpString(naming.resultColumnPrefix)})`,
    `                    .InputListTableInfix(${csharpString(naming.inputListTableInfix)})`,
    `                    .ResultListTableInfix(${csharpString(naming.resultListTableInfix)})`,
    `                    .QueueTable(${csharpString(ir.queueTable.name)})`,
    `                    .InputsTable(${csharpString(ir.inputsTable.name)})`,
    `                    .VarsTable(${csharpString(ir.varsTable.name)})`,
    `                    .ControlTable(${csharpString(ir.controlTable.name)}))`,
    // All fourteen column values are always emitted explicitly, in
    // SqliteHostColumns property order (docs/csharp-api.md).
    "                .Columns(c => c",
    `                    .CallId(${csharpString(columns.callId)})`,
    `                    .ItemIndex(${csharpString(columns.itemIndex)})`,
    `                    .Status(${csharpString(columns.status)})`,
    `                    .DoneValue(${csharpString(columns.doneValue)})`,
    `                    .QueueId(${csharpString(columns.queueId)})`,
    `                    .Method(${csharpString(columns.method)})`,
    `                    .Name(${csharpString(columns.name)})`,
    `                    .ValueType(${csharpString(columns.valueType)})`,
    `                    .IntValue(${csharpString(columns.intValue)})`,
    `                    .RealValue(${csharpString(columns.realValue)})`,
    `                    .TextValue(${csharpString(columns.textValue)})`,
    `                    .BlobValue(${csharpString(columns.blobValue)})`,
    `                    .Action(${csharpString(columns.action)})`,
    `                    .Message(${csharpString(columns.message)}))`,
    "                .Methods(GeneratedHostMethodSpecs.BuildAll());",
    "        }",
    "    }",
    "}",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// GeneratedSchemaSql.g.cs
// ---------------------------------------------------------------------------

export function emitSchemaSql(ir: HostLibraryIr): string {
  const script = generateSchemaScript(ir);
  const scriptLines = script.split("\n");
  // generateSchemaScript output ends with "\n"; drop the empty tail.
  scriptLines.pop();
  const segments = scriptLines.map((line) => csharpString(`${line}\n`));
  const literal = segments.map((segment, i) =>
    i === 0 ? `            ${segment}` : `            + ${segment}`,
  );
  literal[literal.length - 1] += ";";
  return [
    HEADER,
    "",
    `namespace ${generatedNamespace(ir)}`,
    "{",
    "    public static class GeneratedSchemaSql",
    "    {",
    "        public const string SchemaScript =",
    ...literal,
    "    }",
    "}",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// ScriptEnvelope.g.cs (protocol v1, app-independent, vendored)
// ---------------------------------------------------------------------------

export function emitScriptEnvelope(): string {
  return [
    HEADER,
    "",
    "using System.Collections.Generic;",
    "",
    "namespace SqliteHost",
    "{",
    "    public class SqliteHostScript",
    "    {",
    "        public string Engine { get; set; }",
    "        public string ScriptId { get; set; }",
    "        public int RequiredApiLevel { get; set; }",
    "        public List<string> RequiredFeatures { get; set; }",
    "        public List<string> RequiredMethods { get; set; }",
    "        public List<SqliteHostRuntimeInput> Inputs { get; set; }",
    "        public List<SqliteHostStep> Steps { get; set; }",
    "    }",
    "",
    "    public class SqliteHostRuntimeInput",
    "    {",
    "        public string Name { get; set; }",
    "        public SqliteHostBindingValue Value { get; set; }",
    "    }",
    "",
    "    public class SqliteHostStep",
    "    {",
    "        public string Id { get; set; }",
    "        public List<SqliteHostStatement> Statements { get; set; }",
    "    }",
    "",
    "    public class SqliteHostStatement",
    "    {",
    "        public string Sql { get; set; }",
    "        public Dictionary<string, SqliteHostBindingValue> Bindings { get; set; }",
    "    }",
    "}",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/** Emit all generated C# sources for a host library IR. */
export function emitCSharp(ir: HostLibraryIr): EmittedFile[] {
  return [
    { path: DTOS_FILE, contents: emitHostMethodDtos(ir) },
    { path: HANDLERS_FILE, contents: emitHandlerInterface(ir) },
    { path: SPECS_FILE, contents: emitMethodSpecs(ir) },
    { path: DEFINITION_FILE, contents: emitHostDefinition(ir) },
    { path: SCHEMA_FILE, contents: emitSchemaSql(ir) },
    { path: ENVELOPE_FILE, contents: emitScriptEnvelope() },
  ];
}
